// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

/**
 * Trust lifecycle values mirror backend AuthDeviceStatus JSON strings:
 * pending, trusted, revoked.
 */
@Suppress("unused")
class AuthDeviceStatus private constructor() {
    companion object {
        const val Pending: Byte = 0
        const val Trusted: Byte = 1
        const val Revoked: Byte = 2
    }
}
