// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Minimal authenticated-device management summary for mobile settings.
 */
@Suppress("unused")
class AuthenticatedDevice : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AuthenticatedDevice {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val userId : ferrex.ids.Uuid get() = userId(ferrex.ids.Uuid())
    fun userId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field userId")
        }
    }
    val fingerprint : String
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field fingerprint")
            }
        }
    val fingerprintAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun fingerprintInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val name : String
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field name")
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val platform : Byte
        get() {
            val o = __offset(12)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val appVersion : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val appVersionAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun appVersionInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val hardwareId : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val hardwareIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(16, 1)
    fun hardwareIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 16, 1)
    val status : Byte
        get() {
            val o = __offset(18)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val pinConfigured : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val failedAttempts : Int
        get() {
            val o = __offset(22)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    val lockedUntil : ferrex.common.Timestamp? get() = lockedUntil(ferrex.common.Timestamp())
    fun lockedUntil(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(24)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val firstAuthenticatedBy : ferrex.ids.Uuid get() = firstAuthenticatedBy(ferrex.ids.Uuid())
    fun firstAuthenticatedBy(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(26)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field firstAuthenticatedBy")
        }
    }
    val firstAuthenticatedAt : ferrex.common.Timestamp get() = firstAuthenticatedAt(ferrex.common.Timestamp())
    fun firstAuthenticatedAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp {
        val o = __offset(28)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field firstAuthenticatedAt")
        }
    }
    val trustedUntil : ferrex.common.Timestamp? get() = trustedUntil(ferrex.common.Timestamp())
    fun trustedUntil(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(30)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val lastSeenAt : ferrex.common.Timestamp get() = lastSeenAt(ferrex.common.Timestamp())
    fun lastSeenAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp {
        val o = __offset(32)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field lastSeenAt")
        }
    }
    val lastActivity : ferrex.common.Timestamp get() = lastActivity(ferrex.common.Timestamp())
    fun lastActivity(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp {
        val o = __offset(34)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field lastActivity")
        }
    }
    val autoLoginEnabled : Boolean
        get() {
            val o = __offset(36)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val revokedBy : ferrex.ids.Uuid? get() = revokedBy(ferrex.ids.Uuid())
    fun revokedBy(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(38)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val revokedAt : ferrex.common.Timestamp? get() = revokedAt(ferrex.common.Timestamp())
    fun revokedAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(40)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val revokedReason : String?
        get() {
            val o = __offset(42)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val revokedReasonAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(42, 1)
    fun revokedReasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 42, 1)
    val createdAt : ferrex.common.Timestamp get() = createdAt(ferrex.common.Timestamp())
    fun createdAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp {
        val o = __offset(44)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field createdAt")
        }
    }
    val updatedAt : ferrex.common.Timestamp get() = updatedAt(ferrex.common.Timestamp())
    fun updatedAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp {
        val o = __offset(46)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field updatedAt")
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAuthenticatedDevice(_bb: ByteBuffer): AuthenticatedDevice = getRootAsAuthenticatedDevice(_bb, AuthenticatedDevice())
        fun getRootAsAuthenticatedDevice(_bb: ByteBuffer, obj: AuthenticatedDevice): AuthenticatedDevice {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startAuthenticatedDevice(builder: FlatBufferBuilder) = builder.startTable(22)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addUserId(builder: FlatBufferBuilder, userId: Int) = builder.addStruct(1, userId, 0)
        fun addFingerprint(builder: FlatBufferBuilder, fingerprint: Int) = builder.addOffset(2, fingerprint, 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(3, name, 0)
        fun addPlatform(builder: FlatBufferBuilder, platform: Byte) = builder.addByte(4, platform, 0)
        fun addAppVersion(builder: FlatBufferBuilder, appVersion: Int) = builder.addOffset(5, appVersion, 0)
        fun addHardwareId(builder: FlatBufferBuilder, hardwareId: Int) = builder.addOffset(6, hardwareId, 0)
        fun addStatus(builder: FlatBufferBuilder, status: Byte) = builder.addByte(7, status, 0)
        fun addPinConfigured(builder: FlatBufferBuilder, pinConfigured: Boolean) = builder.addBoolean(8, pinConfigured, false)
        fun addFailedAttempts(builder: FlatBufferBuilder, failedAttempts: Int) = builder.addInt(9, failedAttempts, 0)
        fun addLockedUntil(builder: FlatBufferBuilder, lockedUntil: Int) = builder.addStruct(10, lockedUntil, 0)
        fun addFirstAuthenticatedBy(builder: FlatBufferBuilder, firstAuthenticatedBy: Int) = builder.addStruct(11, firstAuthenticatedBy, 0)
        fun addFirstAuthenticatedAt(builder: FlatBufferBuilder, firstAuthenticatedAt: Int) = builder.addStruct(12, firstAuthenticatedAt, 0)
        fun addTrustedUntil(builder: FlatBufferBuilder, trustedUntil: Int) = builder.addStruct(13, trustedUntil, 0)
        fun addLastSeenAt(builder: FlatBufferBuilder, lastSeenAt: Int) = builder.addStruct(14, lastSeenAt, 0)
        fun addLastActivity(builder: FlatBufferBuilder, lastActivity: Int) = builder.addStruct(15, lastActivity, 0)
        fun addAutoLoginEnabled(builder: FlatBufferBuilder, autoLoginEnabled: Boolean) = builder.addBoolean(16, autoLoginEnabled, false)
        fun addRevokedBy(builder: FlatBufferBuilder, revokedBy: Int) = builder.addStruct(17, revokedBy, 0)
        fun addRevokedAt(builder: FlatBufferBuilder, revokedAt: Int) = builder.addStruct(18, revokedAt, 0)
        fun addRevokedReason(builder: FlatBufferBuilder, revokedReason: Int) = builder.addOffset(19, revokedReason, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: Int) = builder.addStruct(20, createdAt, 0)
        fun addUpdatedAt(builder: FlatBufferBuilder, updatedAt: Int) = builder.addStruct(21, updatedAt, 0)
        fun endAuthenticatedDevice(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 8)
                builder.required(o, 10)
                builder.required(o, 26)
                builder.required(o, 28)
                builder.required(o, 32)
                builder.required(o, 34)
                builder.required(o, 44)
                builder.required(o, 46)
            return o
        }
    }
}
