// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AuthenticatedDevicesResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AuthenticatedDevicesResponse {
        __init(_i, _bb)
        return this
    }
    fun devices(j: Int) : ferrex.auth.AuthenticatedDevice? = devices(ferrex.auth.AuthenticatedDevice(), j)
    fun devices(obj: ferrex.auth.AuthenticatedDevice, j: Int) : ferrex.auth.AuthenticatedDevice? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val devicesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAuthenticatedDevicesResponse(_bb: ByteBuffer): AuthenticatedDevicesResponse = getRootAsAuthenticatedDevicesResponse(_bb, AuthenticatedDevicesResponse())
        fun getRootAsAuthenticatedDevicesResponse(_bb: ByteBuffer, obj: AuthenticatedDevicesResponse): AuthenticatedDevicesResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createAuthenticatedDevicesResponse(builder: FlatBufferBuilder, devicesOffset: Int) : Int {
            builder.startTable(1)
            addDevices(builder, devicesOffset)
            return endAuthenticatedDevicesResponse(builder)
        }
        fun startAuthenticatedDevicesResponse(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addDevices(builder: FlatBufferBuilder, devices: Int) = builder.addOffset(0, devices, 0)
        fun createDevicesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startDevicesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endAuthenticatedDevicesResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
