// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class AuthToken : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : AuthToken {
        __init(_i, _bb)
        return this
    }
    val accessToken : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field accessToken")
            }
        }
    val accessTokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun accessTokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val refreshToken : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field refreshToken")
            }
        }
    val refreshTokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun refreshTokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val expiresIn : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val sessionId : ferrex.ids.Uuid? get() = sessionId(ferrex.ids.Uuid())
    fun sessionId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val deviceSessionId : ferrex.ids.Uuid? get() = deviceSessionId(ferrex.ids.Uuid())
    fun deviceSessionId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val userId : ferrex.ids.Uuid? get() = userId(ferrex.ids.Uuid())
    fun userId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val scope : Byte
        get() {
            val o = __offset(16)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsAuthToken(_bb: ByteBuffer): AuthToken = getRootAsAuthToken(_bb, AuthToken())
        fun getRootAsAuthToken(_bb: ByteBuffer, obj: AuthToken): AuthToken {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startAuthToken(builder: FlatBufferBuilder) = builder.startTable(7)
        fun addAccessToken(builder: FlatBufferBuilder, accessToken: Int) = builder.addOffset(0, accessToken, 0)
        fun addRefreshToken(builder: FlatBufferBuilder, refreshToken: Int) = builder.addOffset(1, refreshToken, 0)
        fun addExpiresIn(builder: FlatBufferBuilder, expiresIn: UInt) = builder.addInt(2, expiresIn.toInt(), 0)
        fun addSessionId(builder: FlatBufferBuilder, sessionId: Int) = builder.addStruct(3, sessionId, 0)
        fun addDeviceSessionId(builder: FlatBufferBuilder, deviceSessionId: Int) = builder.addStruct(4, deviceSessionId, 0)
        fun addUserId(builder: FlatBufferBuilder, userId: Int) = builder.addStruct(5, userId, 0)
        fun addScope(builder: FlatBufferBuilder, scope: Byte) = builder.addByte(6, scope, 0)
        fun endAuthToken(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
            return o
        }
        fun finishAuthTokenBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedAuthTokenBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
