// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Device registration summary returned with device password/PIN login.
 */
@Suppress("unused")
class DeviceRegistration : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceRegistration {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val userId : ferrex.ids.Uuid get() = userId(ferrex.ids.Uuid())
    fun userId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field userId")
        }
    }
    val deviceId : ferrex.ids.Uuid get() = deviceId(ferrex.ids.Uuid())
    fun deviceId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field deviceId")
        }
    }
    val deviceName : String
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field deviceName")
            }
        }
    val deviceNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun deviceNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val platform : Byte
        get() {
            val o = __offset(12)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val appVersion : String
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field appVersion")
            }
        }
    val appVersionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun appVersionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    val pinConfigured : Boolean
        get() {
            val o = __offset(16)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val registeredAt : ferrex.common.Timestamp get() = registeredAt(ferrex.common.Timestamp())
    fun registeredAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field registeredAt")
        }
    }
    val lastUsedAt : ferrex.common.Timestamp get() = lastUsedAt(ferrex.common.Timestamp())
    fun lastUsedAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field lastUsedAt")
        }
    }
    val expiresAt : ferrex.common.Timestamp? get() = expiresAt(ferrex.common.Timestamp())
    fun expiresAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val revoked : Boolean
        get() {
            val o = __offset(24)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val revokedBy : ferrex.ids.Uuid? get() = revokedBy(ferrex.ids.Uuid())
    fun revokedBy(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(26)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val revokedAt : ferrex.common.Timestamp? get() = revokedAt(ferrex.common.Timestamp())
    fun revokedAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(28)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceRegistration(_bb: ByteBuffer): DeviceRegistration = getRootAsDeviceRegistration(_bb, DeviceRegistration())
        fun getRootAsDeviceRegistration(_bb: ByteBuffer, obj: DeviceRegistration): DeviceRegistration {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startDeviceRegistration(builder: FlatBufferBuilder) = builder.startTable(13)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addUserId(builder: FlatBufferBuilder, userId: Int) = builder.addStruct(1, userId, 0)
        fun addDeviceId(builder: FlatBufferBuilder, deviceId: Int) = builder.addStruct(2, deviceId, 0)
        fun addDeviceName(builder: FlatBufferBuilder, deviceName: Int) = builder.addOffset(3, deviceName, 0)
        fun addPlatform(builder: FlatBufferBuilder, platform: Byte) = builder.addByte(4, platform, 0)
        fun addAppVersion(builder: FlatBufferBuilder, appVersion: Int) = builder.addOffset(5, appVersion, 0)
        fun addPinConfigured(builder: FlatBufferBuilder, pinConfigured: Boolean) = builder.addBoolean(6, pinConfigured, false)
        fun addRegisteredAt(builder: FlatBufferBuilder, registeredAt: Int) = builder.addStruct(7, registeredAt, 0)
        fun addLastUsedAt(builder: FlatBufferBuilder, lastUsedAt: Int) = builder.addStruct(8, lastUsedAt, 0)
        fun addExpiresAt(builder: FlatBufferBuilder, expiresAt: Int) = builder.addStruct(9, expiresAt, 0)
        fun addRevoked(builder: FlatBufferBuilder, revoked: Boolean) = builder.addBoolean(10, revoked, false)
        fun addRevokedBy(builder: FlatBufferBuilder, revokedBy: Int) = builder.addStruct(11, revokedBy, 0)
        fun addRevokedAt(builder: FlatBufferBuilder, revokedAt: Int) = builder.addStruct(12, revokedAt, 0)
        fun endDeviceRegistration(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 8)
                builder.required(o, 10)
                builder.required(o, 14)
                builder.required(o, 18)
                builder.required(o, 20)
            return o
        }
    }
}
