// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Device information sent during password login/profile lookup.
 */
@Suppress("unused")
class DeviceInfo : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceInfo {
        __init(_i, _bb)
        return this
    }
    val deviceId : ferrex.ids.Uuid get() = deviceId(ferrex.ids.Uuid())
    fun deviceId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field deviceId")
        }
    }
    val deviceName : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field deviceName")
            }
        }
    val deviceNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun deviceNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val platform : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val appVersion : String
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field appVersion")
            }
        }
    val appVersionAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun appVersionInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val hardwareId : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val hardwareIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun hardwareIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceInfo(_bb: ByteBuffer): DeviceInfo = getRootAsDeviceInfo(_bb, DeviceInfo())
        fun getRootAsDeviceInfo(_bb: ByteBuffer, obj: DeviceInfo): DeviceInfo {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startDeviceInfo(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addDeviceId(builder: FlatBufferBuilder, deviceId: Int) = builder.addStruct(0, deviceId, 0)
        fun addDeviceName(builder: FlatBufferBuilder, deviceName: Int) = builder.addOffset(1, deviceName, 0)
        fun addPlatform(builder: FlatBufferBuilder, platform: Byte) = builder.addByte(2, platform, 0)
        fun addAppVersion(builder: FlatBufferBuilder, appVersion: Int) = builder.addOffset(3, appVersion, 0)
        fun addHardwareId(builder: FlatBufferBuilder, hardwareId: Int) = builder.addOffset(4, hardwareId, 0)
        fun endDeviceInfo(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 10)
            return o
        }
    }
}
