// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Password/device login request for /auth/device/login.
 */
@Suppress("unused")
class DeviceLoginRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceLoginRequest {
        __init(_i, _bb)
        return this
    }
    val username : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field username")
            }
        }
    val usernameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun usernameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val password : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field password")
            }
        }
    val passwordAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun passwordInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val deviceInfo : ferrex.auth.DeviceInfo? get() = deviceInfo(ferrex.auth.DeviceInfo())
    fun deviceInfo(obj: ferrex.auth.DeviceInfo) : ferrex.auth.DeviceInfo? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val rememberDevice : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val devicePublicKey : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val devicePublicKeyAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun devicePublicKeyInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val deviceKeyAlg : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val deviceKeyAlgAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun deviceKeyAlgInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceLoginRequest(_bb: ByteBuffer): DeviceLoginRequest = getRootAsDeviceLoginRequest(_bb, DeviceLoginRequest())
        fun getRootAsDeviceLoginRequest(_bb: ByteBuffer, obj: DeviceLoginRequest): DeviceLoginRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDeviceLoginRequest(builder: FlatBufferBuilder, usernameOffset: Int, passwordOffset: Int, deviceInfoOffset: Int, rememberDevice: Boolean, devicePublicKeyOffset: Int, deviceKeyAlgOffset: Int) : Int {
            builder.startTable(6)
            addDeviceKeyAlg(builder, deviceKeyAlgOffset)
            addDevicePublicKey(builder, devicePublicKeyOffset)
            addDeviceInfo(builder, deviceInfoOffset)
            addPassword(builder, passwordOffset)
            addUsername(builder, usernameOffset)
            addRememberDevice(builder, rememberDevice)
            return endDeviceLoginRequest(builder)
        }
        fun startDeviceLoginRequest(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addUsername(builder: FlatBufferBuilder, username: Int) = builder.addOffset(0, username, 0)
        fun addPassword(builder: FlatBufferBuilder, password: Int) = builder.addOffset(1, password, 0)
        fun addDeviceInfo(builder: FlatBufferBuilder, deviceInfo: Int) = builder.addOffset(2, deviceInfo, 0)
        fun addRememberDevice(builder: FlatBufferBuilder, rememberDevice: Boolean) = builder.addBoolean(3, rememberDevice, false)
        fun addDevicePublicKey(builder: FlatBufferBuilder, devicePublicKey: Int) = builder.addOffset(4, devicePublicKey, 0)
        fun addDeviceKeyAlg(builder: FlatBufferBuilder, deviceKeyAlg: Int) = builder.addOffset(5, deviceKeyAlg, 0)
        fun endDeviceLoginRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
            return o
        }
    }
}
