// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DeviceAuthStatus : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceAuthStatus {
        __init(_i, _bb)
        return this
    }
    val deviceRegistered : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hasPin : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val remainingAttempts : UByte?
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else null
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceAuthStatus(_bb: ByteBuffer): DeviceAuthStatus = getRootAsDeviceAuthStatus(_bb, DeviceAuthStatus())
        fun getRootAsDeviceAuthStatus(_bb: ByteBuffer, obj: DeviceAuthStatus): DeviceAuthStatus {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDeviceAuthStatus(builder: FlatBufferBuilder, deviceRegistered: Boolean, hasPin: Boolean, remainingAttempts: UByte?) : Int {
            builder.startTable(3)
            remainingAttempts?.run { addRemainingAttempts(builder, remainingAttempts) }
            addHasPin(builder, hasPin)
            addDeviceRegistered(builder, deviceRegistered)
            return endDeviceAuthStatus(builder)
        }
        fun startDeviceAuthStatus(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addDeviceRegistered(builder: FlatBufferBuilder, deviceRegistered: Boolean) = builder.addBoolean(0, deviceRegistered, false)
        fun addHasPin(builder: FlatBufferBuilder, hasPin: Boolean) = builder.addBoolean(1, hasPin, false)
        fun addRemainingAttempts(builder: FlatBufferBuilder, remainingAttempts: UByte) = builder.addByte(2, remainingAttempts.toByte(), 0)
        fun endDeviceAuthStatus(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
