// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * AuthToken-shaped response returned by device password login and PIN login.
 */
@Suppress("unused")
class DeviceLoginResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceLoginResponse {
        __init(_i, _bb)
        return this
    }
    val accessToken : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field accessToken")
            }
        }
    val accessTokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun accessTokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    /**
     * Backwards-compatible alias for older device clients.
     */
    val sessionToken : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field sessionToken")
            }
        }
    val sessionTokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun sessionTokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val refreshToken : String
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field refreshToken")
            }
        }
    val refreshTokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun refreshTokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val expiresIn : UInt
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val sessionId : ferrex.ids.Uuid? get() = sessionId(ferrex.ids.Uuid())
    fun sessionId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val deviceSessionId : ferrex.ids.Uuid? get() = deviceSessionId(ferrex.ids.Uuid())
    fun deviceSessionId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val userId : ferrex.ids.Uuid? get() = userId(ferrex.ids.Uuid())
    fun userId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val scope : Byte
        get() {
            val o = __offset(18)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val deviceRegistration : ferrex.auth.DeviceRegistration? get() = deviceRegistration(ferrex.auth.DeviceRegistration())
    fun deviceRegistration(obj: ferrex.auth.DeviceRegistration) : ferrex.auth.DeviceRegistration? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val requiresPinSetup : Boolean
        get() {
            val o = __offset(22)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceLoginResponse(_bb: ByteBuffer): DeviceLoginResponse = getRootAsDeviceLoginResponse(_bb, DeviceLoginResponse())
        fun getRootAsDeviceLoginResponse(_bb: ByteBuffer, obj: DeviceLoginResponse): DeviceLoginResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startDeviceLoginResponse(builder: FlatBufferBuilder) = builder.startTable(10)
        fun addAccessToken(builder: FlatBufferBuilder, accessToken: Int) = builder.addOffset(0, accessToken, 0)
        fun addSessionToken(builder: FlatBufferBuilder, sessionToken: Int) = builder.addOffset(1, sessionToken, 0)
        fun addRefreshToken(builder: FlatBufferBuilder, refreshToken: Int) = builder.addOffset(2, refreshToken, 0)
        fun addExpiresIn(builder: FlatBufferBuilder, expiresIn: UInt) = builder.addInt(3, expiresIn.toInt(), 0)
        fun addSessionId(builder: FlatBufferBuilder, sessionId: Int) = builder.addStruct(4, sessionId, 0)
        fun addDeviceSessionId(builder: FlatBufferBuilder, deviceSessionId: Int) = builder.addStruct(5, deviceSessionId, 0)
        fun addUserId(builder: FlatBufferBuilder, userId: Int) = builder.addStruct(6, userId, 0)
        fun addScope(builder: FlatBufferBuilder, scope: Byte) = builder.addByte(7, scope, 0)
        fun addDeviceRegistration(builder: FlatBufferBuilder, deviceRegistration: Int) = builder.addOffset(8, deviceRegistration, 0)
        fun addRequiresPinSetup(builder: FlatBufferBuilder, requiresPinSetup: Boolean) = builder.addBoolean(9, requiresPinSetup, false)
        fun endDeviceLoginResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 8)
            return o
        }
    }
}
