// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class DeviceTrustPolicy : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeviceTrustPolicy {
        __init(_i, _bb)
        return this
    }
    val rememberDeviceDefault : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val trustDurationDays : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val pinMaxAttempts : UByte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val pinLockoutMinutes : UShort
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val adminPinUnlockEnabled : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeviceTrustPolicy(_bb: ByteBuffer): DeviceTrustPolicy = getRootAsDeviceTrustPolicy(_bb, DeviceTrustPolicy())
        fun getRootAsDeviceTrustPolicy(_bb: ByteBuffer, obj: DeviceTrustPolicy): DeviceTrustPolicy {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDeviceTrustPolicy(builder: FlatBufferBuilder, rememberDeviceDefault: Boolean, trustDurationDays: UShort, pinMaxAttempts: UByte, pinLockoutMinutes: UShort, adminPinUnlockEnabled: Boolean) : Int {
            builder.startTable(5)
            addPinLockoutMinutes(builder, pinLockoutMinutes)
            addTrustDurationDays(builder, trustDurationDays)
            addAdminPinUnlockEnabled(builder, adminPinUnlockEnabled)
            addPinMaxAttempts(builder, pinMaxAttempts)
            addRememberDeviceDefault(builder, rememberDeviceDefault)
            return endDeviceTrustPolicy(builder)
        }
        fun startDeviceTrustPolicy(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addRememberDeviceDefault(builder: FlatBufferBuilder, rememberDeviceDefault: Boolean) = builder.addBoolean(0, rememberDeviceDefault, false)
        fun addTrustDurationDays(builder: FlatBufferBuilder, trustDurationDays: UShort) = builder.addShort(1, trustDurationDays.toShort(), 0)
        fun addPinMaxAttempts(builder: FlatBufferBuilder, pinMaxAttempts: UByte) = builder.addByte(2, pinMaxAttempts.toByte(), 0)
        fun addPinLockoutMinutes(builder: FlatBufferBuilder, pinLockoutMinutes: UShort) = builder.addShort(3, pinLockoutMinutes.toShort(), 0)
        fun addAdminPinUnlockEnabled(builder: FlatBufferBuilder, adminPinUnlockEnabled: Boolean) = builder.addBoolean(4, adminPinUnlockEnabled, false)
        fun endDeviceTrustPolicy(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
