// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Minimal pre-auth user card returned only for known devices.
 */
@Suppress("unused")
class KnownDeviceUserCard : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : KnownDeviceUserCard {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val username : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field username")
            }
        }
    val usernameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun usernameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val displayName : String
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field displayName")
            }
        }
    val displayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun displayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val avatarUrl : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val avatarUrlAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun avatarUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val hasPin : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsKnownDeviceUserCard(_bb: ByteBuffer): KnownDeviceUserCard = getRootAsKnownDeviceUserCard(_bb, KnownDeviceUserCard())
        fun getRootAsKnownDeviceUserCard(_bb: ByteBuffer, obj: KnownDeviceUserCard): KnownDeviceUserCard {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startKnownDeviceUserCard(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addUsername(builder: FlatBufferBuilder, username: Int) = builder.addOffset(1, username, 0)
        fun addDisplayName(builder: FlatBufferBuilder, displayName: Int) = builder.addOffset(2, displayName, 0)
        fun addAvatarUrl(builder: FlatBufferBuilder, avatarUrl: Int) = builder.addOffset(3, avatarUrl, 0)
        fun addHasPin(builder: FlatBufferBuilder, hasPin: Boolean) = builder.addBoolean(4, hasPin, false)
        fun endKnownDeviceUserCard(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 8)
            return o
        }
    }
}
