// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class KnownDeviceProfilesResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : KnownDeviceProfilesResponse {
        __init(_i, _bb)
        return this
    }
    val knownDevice : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun users(j: Int) : ferrex.auth.KnownDeviceUserCard? = users(ferrex.auth.KnownDeviceUserCard(), j)
    fun users(obj: ferrex.auth.KnownDeviceUserCard, j: Int) : ferrex.auth.KnownDeviceUserCard? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val usersLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsKnownDeviceProfilesResponse(_bb: ByteBuffer): KnownDeviceProfilesResponse = getRootAsKnownDeviceProfilesResponse(_bb, KnownDeviceProfilesResponse())
        fun getRootAsKnownDeviceProfilesResponse(_bb: ByteBuffer, obj: KnownDeviceProfilesResponse): KnownDeviceProfilesResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createKnownDeviceProfilesResponse(builder: FlatBufferBuilder, knownDevice: Boolean, usersOffset: Int) : Int {
            builder.startTable(2)
            addUsers(builder, usersOffset)
            addKnownDevice(builder, knownDevice)
            return endKnownDeviceProfilesResponse(builder)
        }
        fun startKnownDeviceProfilesResponse(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addKnownDevice(builder: FlatBufferBuilder, knownDevice: Boolean) = builder.addBoolean(0, knownDevice, false)
        fun addUsers(builder: FlatBufferBuilder, users: Int) = builder.addOffset(1, users, 0)
        fun createUsersVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startUsersVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endKnownDeviceProfilesResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
