// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Request body for known-device profile selection.
 */
@Suppress("unused")
class KnownDeviceProfilesRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : KnownDeviceProfilesRequest {
        __init(_i, _bb)
        return this
    }
    val deviceInfo : ferrex.auth.DeviceInfo? get() = deviceInfo(ferrex.auth.DeviceInfo())
    fun deviceInfo(obj: ferrex.auth.DeviceInfo) : ferrex.auth.DeviceInfo? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsKnownDeviceProfilesRequest(_bb: ByteBuffer): KnownDeviceProfilesRequest = getRootAsKnownDeviceProfilesRequest(_bb, KnownDeviceProfilesRequest())
        fun getRootAsKnownDeviceProfilesRequest(_bb: ByteBuffer, obj: KnownDeviceProfilesRequest): KnownDeviceProfilesRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createKnownDeviceProfilesRequest(builder: FlatBufferBuilder, deviceInfoOffset: Int) : Int {
            builder.startTable(1)
            addDeviceInfo(builder, deviceInfoOffset)
            return endKnownDeviceProfilesRequest(builder)
        }
        fun startKnownDeviceProfilesRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addDeviceInfo(builder: FlatBufferBuilder, deviceInfo: Int) = builder.addOffset(0, deviceInfo, 0)
        fun endKnownDeviceProfilesRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
