// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class LoginRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : LoginRequest {
        __init(_i, _bb)
        return this
    }
    val username : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field username")
            }
        }
    val usernameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun usernameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val password : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field password")
            }
        }
    val passwordAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun passwordInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val deviceName : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val deviceNameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun deviceNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsLoginRequest(_bb: ByteBuffer): LoginRequest = getRootAsLoginRequest(_bb, LoginRequest())
        fun getRootAsLoginRequest(_bb: ByteBuffer, obj: LoginRequest): LoginRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createLoginRequest(builder: FlatBufferBuilder, usernameOffset: Int, passwordOffset: Int, deviceNameOffset: Int) : Int {
            builder.startTable(3)
            addDeviceName(builder, deviceNameOffset)
            addPassword(builder, passwordOffset)
            addUsername(builder, usernameOffset)
            return endLoginRequest(builder)
        }
        fun startLoginRequest(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addUsername(builder: FlatBufferBuilder, username: Int) = builder.addOffset(0, username, 0)
        fun addPassword(builder: FlatBufferBuilder, password: Int) = builder.addOffset(1, password, 0)
        fun addDeviceName(builder: FlatBufferBuilder, deviceName: Int) = builder.addOffset(2, deviceName, 0)
        fun endLoginRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
            return o
        }
    }
}
