// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PasswordPolicy : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PasswordPolicy {
        __init(_i, _bb)
        return this
    }
    val enforce : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val minLength : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val requireUppercase : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val requireLowercase : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val requireNumber : Boolean
        get() {
            val o = __offset(12)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val requireSpecial : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPasswordPolicy(_bb: ByteBuffer): PasswordPolicy = getRootAsPasswordPolicy(_bb, PasswordPolicy())
        fun getRootAsPasswordPolicy(_bb: ByteBuffer, obj: PasswordPolicy): PasswordPolicy {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPasswordPolicy(builder: FlatBufferBuilder, enforce: Boolean, minLength: UShort, requireUppercase: Boolean, requireLowercase: Boolean, requireNumber: Boolean, requireSpecial: Boolean) : Int {
            builder.startTable(6)
            addMinLength(builder, minLength)
            addRequireSpecial(builder, requireSpecial)
            addRequireNumber(builder, requireNumber)
            addRequireLowercase(builder, requireLowercase)
            addRequireUppercase(builder, requireUppercase)
            addEnforce(builder, enforce)
            return endPasswordPolicy(builder)
        }
        fun startPasswordPolicy(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addEnforce(builder: FlatBufferBuilder, enforce: Boolean) = builder.addBoolean(0, enforce, false)
        fun addMinLength(builder: FlatBufferBuilder, minLength: UShort) = builder.addShort(1, minLength.toShort(), 0)
        fun addRequireUppercase(builder: FlatBufferBuilder, requireUppercase: Boolean) = builder.addBoolean(2, requireUppercase, false)
        fun addRequireLowercase(builder: FlatBufferBuilder, requireLowercase: Boolean) = builder.addBoolean(3, requireLowercase, false)
        fun addRequireNumber(builder: FlatBufferBuilder, requireNumber: Boolean) = builder.addBoolean(4, requireNumber, false)
        fun addRequireSpecial(builder: FlatBufferBuilder, requireSpecial: Boolean) = builder.addBoolean(5, requireSpecial, false)
        fun endPasswordPolicy(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
