// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PinChallengeResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PinChallengeResponse {
        __init(_i, _bb)
        return this
    }
    val challengeId : ferrex.ids.Uuid get() = challengeId(ferrex.ids.Uuid())
    fun challengeId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field challengeId")
        }
    }
    val nonce : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field nonce")
            }
        }
    val nonceAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun nonceInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val expiresInSecs : Long
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val pinSalt : String
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field pinSalt")
            }
        }
    val pinSaltAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun pinSaltInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPinChallengeResponse(_bb: ByteBuffer): PinChallengeResponse = getRootAsPinChallengeResponse(_bb, PinChallengeResponse())
        fun getRootAsPinChallengeResponse(_bb: ByteBuffer, obj: PinChallengeResponse): PinChallengeResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startPinChallengeResponse(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addChallengeId(builder: FlatBufferBuilder, challengeId: Int) = builder.addStruct(0, challengeId, 0)
        fun addNonce(builder: FlatBufferBuilder, nonce: Int) = builder.addOffset(1, nonce, 0)
        fun addExpiresInSecs(builder: FlatBufferBuilder, expiresInSecs: Long) = builder.addLong(2, expiresInSecs, 0L)
        fun addPinSalt(builder: FlatBufferBuilder, pinSalt: Int) = builder.addOffset(3, pinSalt, 0)
        fun endPinChallengeResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 10)
            return o
        }
    }
}
