// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PinChallengeRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PinChallengeRequest {
        __init(_i, _bb)
        return this
    }
    val deviceId : ferrex.ids.Uuid get() = deviceId(ferrex.ids.Uuid())
    fun deviceId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field deviceId")
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPinChallengeRequest(_bb: ByteBuffer): PinChallengeRequest = getRootAsPinChallengeRequest(_bb, PinChallengeRequest())
        fun getRootAsPinChallengeRequest(_bb: ByteBuffer, obj: PinChallengeRequest): PinChallengeRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startPinChallengeRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addDeviceId(builder: FlatBufferBuilder, deviceId: Int) = builder.addStruct(0, deviceId, 0)
        fun endPinChallengeRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
