// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PinLoginRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PinLoginRequest {
        __init(_i, _bb)
        return this
    }
    val deviceId : ferrex.ids.Uuid get() = deviceId(ferrex.ids.Uuid())
    fun deviceId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field deviceId")
        }
    }
    val clientProof : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field clientProof")
            }
        }
    val clientProofAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun clientProofInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val challengeId : ferrex.ids.Uuid get() = challengeId(ferrex.ids.Uuid())
    fun challengeId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field challengeId")
        }
    }
    val deviceSignature : String
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field deviceSignature")
            }
        }
    val deviceSignatureAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun deviceSignatureInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPinLoginRequest(_bb: ByteBuffer): PinLoginRequest = getRootAsPinLoginRequest(_bb, PinLoginRequest())
        fun getRootAsPinLoginRequest(_bb: ByteBuffer, obj: PinLoginRequest): PinLoginRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startPinLoginRequest(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addDeviceId(builder: FlatBufferBuilder, deviceId: Int) = builder.addStruct(0, deviceId, 0)
        fun addClientProof(builder: FlatBufferBuilder, clientProof: Int) = builder.addOffset(1, clientProof, 0)
        fun addChallengeId(builder: FlatBufferBuilder, challengeId: Int) = builder.addStruct(2, challengeId, 0)
        fun addDeviceSignature(builder: FlatBufferBuilder, deviceSignature: Int) = builder.addOffset(3, deviceSignature, 0)
        fun endPinLoginRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 8)
                builder.required(o, 10)
            return o
        }
    }
}
