// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PinPolicy : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PinPolicy {
        __init(_i, _bb)
        return this
    }
    val minLength : UShort
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val maxLength : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val requireNumeric : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val rejectRepeatedDigits : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val maxConsecutiveIdentical : UShort
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val rejectSequentialDigits : Boolean
        get() {
            val o = __offset(14)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPinPolicy(_bb: ByteBuffer): PinPolicy = getRootAsPinPolicy(_bb, PinPolicy())
        fun getRootAsPinPolicy(_bb: ByteBuffer, obj: PinPolicy): PinPolicy {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPinPolicy(builder: FlatBufferBuilder, minLength: UShort, maxLength: UShort, requireNumeric: Boolean, rejectRepeatedDigits: Boolean, maxConsecutiveIdentical: UShort, rejectSequentialDigits: Boolean) : Int {
            builder.startTable(6)
            addMaxConsecutiveIdentical(builder, maxConsecutiveIdentical)
            addMaxLength(builder, maxLength)
            addMinLength(builder, minLength)
            addRejectSequentialDigits(builder, rejectSequentialDigits)
            addRejectRepeatedDigits(builder, rejectRepeatedDigits)
            addRequireNumeric(builder, requireNumeric)
            return endPinPolicy(builder)
        }
        fun startPinPolicy(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addMinLength(builder: FlatBufferBuilder, minLength: UShort) = builder.addShort(0, minLength.toShort(), 0)
        fun addMaxLength(builder: FlatBufferBuilder, maxLength: UShort) = builder.addShort(1, maxLength.toShort(), 0)
        fun addRequireNumeric(builder: FlatBufferBuilder, requireNumeric: Boolean) = builder.addBoolean(2, requireNumeric, false)
        fun addRejectRepeatedDigits(builder: FlatBufferBuilder, rejectRepeatedDigits: Boolean) = builder.addBoolean(3, rejectRepeatedDigits, false)
        fun addMaxConsecutiveIdentical(builder: FlatBufferBuilder, maxConsecutiveIdentical: UShort) = builder.addShort(4, maxConsecutiveIdentical.toShort(), 0)
        fun addRejectSequentialDigits(builder: FlatBufferBuilder, rejectSequentialDigits: Boolean) = builder.addBoolean(5, rejectSequentialDigits, false)
        fun endPinPolicy(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
