// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

/**
 * Device platform values mirror the backend JSON strings:
 * unknown, macos, linux, windows, ios, android, tvos, web.
 */
@Suppress("unused")
class Platform private constructor() {
    companion object {
        const val Unknown: Byte = 0
        const val MacOS: Byte = 1
        const val Linux: Byte = 2
        const val Windows: Byte = 3
        const val IOS: Byte = 4
        const val Android: Byte = 5
        const val TvOS: Byte = 6
        const val Web: Byte = 7
    }
}
