// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class RefreshRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RefreshRequest {
        __init(_i, _bb)
        return this
    }
    val refreshToken : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field refreshToken")
            }
        }
    val refreshTokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun refreshTokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRefreshRequest(_bb: ByteBuffer): RefreshRequest = getRootAsRefreshRequest(_bb, RefreshRequest())
        fun getRootAsRefreshRequest(_bb: ByteBuffer, obj: RefreshRequest): RefreshRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRefreshRequest(builder: FlatBufferBuilder, refreshTokenOffset: Int) : Int {
            builder.startTable(1)
            addRefreshToken(builder, refreshTokenOffset)
            return endRefreshRequest(builder)
        }
        fun startRefreshRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addRefreshToken(builder: FlatBufferBuilder, refreshToken: Int) = builder.addOffset(0, refreshToken, 0)
        fun endRefreshRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
