// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

@Suppress("unused")
class SessionScope private constructor() {
    companion object {
        const val Full: Byte = 0
        const val Playback: Byte = 1
    }
}
