// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SetupStatus : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SetupStatus {
        __init(_i, _bb)
        return this
    }
    val needsSetup : Boolean
        get() {
            val o = __offset(4)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val hasAdmin : Boolean
        get() {
            val o = __offset(6)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val requiresSetupToken : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val userCount : UInt
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val libraryCount : UInt
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val adminPasswordPolicy : ferrex.auth.PasswordPolicy? get() = adminPasswordPolicy(ferrex.auth.PasswordPolicy())
    fun adminPasswordPolicy(obj: ferrex.auth.PasswordPolicy) : ferrex.auth.PasswordPolicy? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val userPasswordPolicy : ferrex.auth.PasswordPolicy? get() = userPasswordPolicy(ferrex.auth.PasswordPolicy())
    fun userPasswordPolicy(obj: ferrex.auth.PasswordPolicy) : ferrex.auth.PasswordPolicy? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val pinPolicy : ferrex.auth.PinPolicy? get() = pinPolicy(ferrex.auth.PinPolicy())
    fun pinPolicy(obj: ferrex.auth.PinPolicy) : ferrex.auth.PinPolicy? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val deviceTrustPolicy : ferrex.auth.DeviceTrustPolicy? get() = deviceTrustPolicy(ferrex.auth.DeviceTrustPolicy())
    fun deviceTrustPolicy(obj: ferrex.auth.DeviceTrustPolicy) : ferrex.auth.DeviceTrustPolicy? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSetupStatus(_bb: ByteBuffer): SetupStatus = getRootAsSetupStatus(_bb, SetupStatus())
        fun getRootAsSetupStatus(_bb: ByteBuffer, obj: SetupStatus): SetupStatus {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSetupStatus(builder: FlatBufferBuilder, needsSetup: Boolean, hasAdmin: Boolean, requiresSetupToken: Boolean, userCount: UInt, libraryCount: UInt, adminPasswordPolicyOffset: Int, userPasswordPolicyOffset: Int, pinPolicyOffset: Int, deviceTrustPolicyOffset: Int) : Int {
            builder.startTable(9)
            addDeviceTrustPolicy(builder, deviceTrustPolicyOffset)
            addPinPolicy(builder, pinPolicyOffset)
            addUserPasswordPolicy(builder, userPasswordPolicyOffset)
            addAdminPasswordPolicy(builder, adminPasswordPolicyOffset)
            addLibraryCount(builder, libraryCount)
            addUserCount(builder, userCount)
            addRequiresSetupToken(builder, requiresSetupToken)
            addHasAdmin(builder, hasAdmin)
            addNeedsSetup(builder, needsSetup)
            return endSetupStatus(builder)
        }
        fun startSetupStatus(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addNeedsSetup(builder: FlatBufferBuilder, needsSetup: Boolean) = builder.addBoolean(0, needsSetup, false)
        fun addHasAdmin(builder: FlatBufferBuilder, hasAdmin: Boolean) = builder.addBoolean(1, hasAdmin, false)
        fun addRequiresSetupToken(builder: FlatBufferBuilder, requiresSetupToken: Boolean) = builder.addBoolean(2, requiresSetupToken, false)
        fun addUserCount(builder: FlatBufferBuilder, userCount: UInt) = builder.addInt(3, userCount.toInt(), 0)
        fun addLibraryCount(builder: FlatBufferBuilder, libraryCount: UInt) = builder.addInt(4, libraryCount.toInt(), 0)
        fun addAdminPasswordPolicy(builder: FlatBufferBuilder, adminPasswordPolicy: Int) = builder.addOffset(5, adminPasswordPolicy, 0)
        fun addUserPasswordPolicy(builder: FlatBufferBuilder, userPasswordPolicy: Int) = builder.addOffset(6, userPasswordPolicy, 0)
        fun addPinPolicy(builder: FlatBufferBuilder, pinPolicy: Int) = builder.addOffset(7, pinPolicy, 0)
        fun addDeviceTrustPolicy(builder: FlatBufferBuilder, deviceTrustPolicy: Int) = builder.addOffset(8, deviceTrustPolicy, 0)
        fun endSetupStatus(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
