// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.auth

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class UserProfile : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : UserProfile {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val username : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field username")
            }
        }
    val usernameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun usernameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val displayName : String
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field displayName")
            }
        }
    val displayNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun displayNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val avatarUrl : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val avatarUrlAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun avatarUrlInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val email : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val emailAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun emailInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val createdAt : ferrex.common.Timestamp? get() = createdAt(ferrex.common.Timestamp())
    fun createdAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val updatedAt : ferrex.common.Timestamp? get() = updatedAt(ferrex.common.Timestamp())
    fun updatedAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val lastLogin : ferrex.common.Timestamp? get() = lastLogin(ferrex.common.Timestamp())
    fun lastLogin(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val isActive : Boolean
        get() {
            val o = __offset(20)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else true
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsUserProfile(_bb: ByteBuffer): UserProfile = getRootAsUserProfile(_bb, UserProfile())
        fun getRootAsUserProfile(_bb: ByteBuffer, obj: UserProfile): UserProfile {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startUserProfile(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addUsername(builder: FlatBufferBuilder, username: Int) = builder.addOffset(1, username, 0)
        fun addDisplayName(builder: FlatBufferBuilder, displayName: Int) = builder.addOffset(2, displayName, 0)
        fun addAvatarUrl(builder: FlatBufferBuilder, avatarUrl: Int) = builder.addOffset(3, avatarUrl, 0)
        fun addEmail(builder: FlatBufferBuilder, email: Int) = builder.addOffset(4, email, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: Int) = builder.addStruct(5, createdAt, 0)
        fun addUpdatedAt(builder: FlatBufferBuilder, updatedAt: Int) = builder.addStruct(6, updatedAt, 0)
        fun addLastLogin(builder: FlatBufferBuilder, lastLogin: Int) = builder.addStruct(7, lastLogin, 0)
        fun addIsActive(builder: FlatBufferBuilder, isActive: Boolean) = builder.addBoolean(8, isActive, true)
        fun endUserProfile(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 8)
            return o
        }
    }
}
