// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.common

/**
 * Image kind used by the mobile image manifest/readiness contracts.
 */
@Suppress("unused")
class ImageCategory private constructor() {
    companion object {
        const val Poster: Byte = 0
        const val Backdrop: Byte = 1
        const val Profile: Byte = 2
        const val Episode: Byte = 3
    }
}
