// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.common

/**
 * Library content type.
 */
@Suppress("unused")
class LibraryType private constructor() {
    companion object {
        const val Movies: Byte = 0
        const val Series: Byte = 1
    }
}
