// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.common

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class PaginationMeta : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : PaginationMeta {
        __init(_i, _bb)
        return this
    }
    val total : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val page : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val pageSize : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val hasMore : Boolean
        get() {
            val o = __offset(10)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsPaginationMeta(_bb: ByteBuffer): PaginationMeta = getRootAsPaginationMeta(_bb, PaginationMeta())
        fun getRootAsPaginationMeta(_bb: ByteBuffer, obj: PaginationMeta): PaginationMeta {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createPaginationMeta(builder: FlatBufferBuilder, total: UInt, page: UInt, pageSize: UInt, hasMore: Boolean) : Int {
            builder.startTable(4)
            addPageSize(builder, pageSize)
            addPage(builder, page)
            addTotal(builder, total)
            addHasMore(builder, hasMore)
            return endPaginationMeta(builder)
        }
        fun startPaginationMeta(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addTotal(builder: FlatBufferBuilder, total: UInt) = builder.addInt(0, total.toInt(), 0)
        fun addPage(builder: FlatBufferBuilder, page: UInt) = builder.addInt(1, page.toInt(), 0)
        fun addPageSize(builder: FlatBufferBuilder, pageSize: UInt) = builder.addInt(2, pageSize.toInt(), 0)
        fun addHasMore(builder: FlatBufferBuilder, hasMore: Boolean) = builder.addBoolean(3, hasMore, false)
        fun endPaginationMeta(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
