// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.common

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * UTC timestamp as milliseconds since the Unix epoch.
 * A zero value represents an absent optional timestamp in legacy endpoints.
 */
@Suppress("unused")
class Timestamp : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Timestamp {
        __init(_i, _bb)
        return this
    }
    val millis : Long get() = bb.getLong(bb_pos + 0)
    companion object {
        fun createTimestamp(builder: FlatBufferBuilder, millis: Long) : Int {
            builder.prep(8, 8)
            builder.putLong(millis)
            return builder.offset()
        }
    }
}
