// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.common

/**
 * Video/media discriminator used for file ownership and media references.
 */
@Suppress("unused")
class VideoMediaType private constructor() {
    companion object {
        const val Movie: Byte = 0
        const val Series: Byte = 1
        const val Season: Byte = 2
        const val Episode: Byte = 3
    }
}
