-- Durable replay outbox for catalog/media invalidation events consumed by
-- /api/v1/events/media.

CREATE SCHEMA IF NOT EXISTS ferrex;

DO $$
DECLARE
    app_schema text;
BEGIN
    SELECT n.nspname
    INTO app_schema
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'libraries'
      AND c.relkind IN ('r', 'p')
      AND n.nspname IN ('ferrex', 'public')
    ORDER BY CASE WHEN n.nspname = 'ferrex' THEN 0 ELSE 1 END
    LIMIT 1;

    IF app_schema IS NULL THEN
        app_schema := 'ferrex';
    END IF;

    PERFORM set_config('search_path', format('%I, public', app_schema), false);
END $$;

CREATE TABLE IF NOT EXISTS catalog_events (
    sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_kind varchar(64) NOT NULL,
    library_id uuid NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,
    entity_kind varchar(64) NOT NULL,
    entity_id uuid,
    movie_batch_id bigint,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    idempotency_key text NOT NULL,
    occurred_at timestamp with time zone NOT NULL DEFAULT NOW(),
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT catalog_events_sequence_check CHECK (sequence > 0),
    CONSTRAINT catalog_events_event_kind_check CHECK (
        event_kind IN ('movie_batch_finalized', 'series_bundle_finalized')
    ),
    CONSTRAINT catalog_events_entity_kind_check CHECK (
        entity_kind IN ('movie_batch', 'series')
    ),
    CONSTRAINT catalog_events_movie_batch_shape_check CHECK (
        (event_kind = 'movie_batch_finalized'
            AND entity_kind = 'movie_batch'
            AND movie_batch_id IS NOT NULL
            AND movie_batch_id > 0
            AND entity_id IS NULL)
        OR
        (event_kind = 'series_bundle_finalized'
            AND entity_kind = 'series'
            AND entity_id IS NOT NULL
            AND movie_batch_id IS NULL)
    )
);

COMMENT ON TABLE catalog_events IS 'Append-only durable outbox for replaying media catalog events to SSE clients';
COMMENT ON COLUMN catalog_events.sequence IS 'Global monotonic replay cursor used as the SSE event id';
COMMENT ON COLUMN catalog_events.idempotency_key IS 'Stable dedupe key for idempotent finalization/retry paths';
COMMENT ON COLUMN catalog_events.payload IS 'Compact event payload fields for diagnostics and future contract evolution';
COMMENT ON COLUMN catalog_events.occurred_at IS 'Source occurrence time retained for replay windows and future retention policies';
COMMENT ON COLUMN catalog_events.created_at IS 'Outbox insertion time retained for future retention policies';

CREATE UNIQUE INDEX IF NOT EXISTS idx_catalog_events_idempotency_key
    ON catalog_events (idempotency_key);

CREATE INDEX IF NOT EXISTS idx_catalog_events_sequence
    ON catalog_events (sequence);

CREATE INDEX IF NOT EXISTS idx_catalog_events_library_sequence
    ON catalog_events (library_id, sequence);

CREATE INDEX IF NOT EXISTS idx_catalog_events_occurred_at_sequence
    ON catalog_events (occurred_at, sequence);

CREATE INDEX IF NOT EXISTS idx_catalog_events_retention_created_at
    ON catalog_events (created_at);
