// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.image

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ImageReadyEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ImageReadyEvent {
        __init(_i, _bb)
        return this
    }
    val iid : ferrex.ids.Uuid get() = iid(ferrex.ids.Uuid())
    fun iid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field iid")
        }
    }
    val category : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val token : String
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field token")
            }
        }
    val tokenAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun tokenInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsImageReadyEvent(_bb: ByteBuffer): ImageReadyEvent = getRootAsImageReadyEvent(_bb, ImageReadyEvent())
        fun getRootAsImageReadyEvent(_bb: ByteBuffer, obj: ImageReadyEvent): ImageReadyEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startImageReadyEvent(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addIid(builder: FlatBufferBuilder, iid: Int) = builder.addStruct(0, iid, 0)
        fun addCategory(builder: FlatBufferBuilder, category: Byte) = builder.addByte(1, category, 0)
        fun addToken(builder: FlatBufferBuilder, token: Int) = builder.addOffset(2, token, 0)
        fun endImageReadyEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 8)
            return o
        }
    }
}
