// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.image

@Suppress("unused")
class ImageStatus private constructor() {
    companion object {
        const val Ready: Byte = 0
        const val Pending: Byte = 1
        const val Failed: Byte = 2
    }
}
