// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.image

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ImageManifestRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ImageManifestRequest {
        __init(_i, _bb)
        return this
    }
    fun queries(j: Int) : ferrex.image.ImageQuery? = queries(ferrex.image.ImageQuery(), j)
    fun queries(obj: ferrex.image.ImageQuery, j: Int) : ferrex.image.ImageQuery? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val queriesLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsImageManifestRequest(_bb: ByteBuffer): ImageManifestRequest = getRootAsImageManifestRequest(_bb, ImageManifestRequest())
        fun getRootAsImageManifestRequest(_bb: ByteBuffer, obj: ImageManifestRequest): ImageManifestRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createImageManifestRequest(builder: FlatBufferBuilder, queriesOffset: Int) : Int {
            builder.startTable(1)
            addQueries(builder, queriesOffset)
            return endImageManifestRequest(builder)
        }
        fun startImageManifestRequest(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addQueries(builder: FlatBufferBuilder, queries: Int) = builder.addOffset(0, queries, 0)
        fun createQueriesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startQueriesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endImageManifestRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
