// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.image

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ImageQuery : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ImageQuery {
        __init(_i, _bb)
        return this
    }
    val iid : ferrex.ids.Uuid get() = iid(ferrex.ids.Uuid())
    fun iid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field iid")
        }
    }
    val category : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsImageQuery(_bb: ByteBuffer): ImageQuery = getRootAsImageQuery(_bb, ImageQuery())
        fun getRootAsImageQuery(_bb: ByteBuffer, obj: ImageQuery): ImageQuery {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startImageQuery(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addIid(builder: FlatBufferBuilder, iid: Int) = builder.addStruct(0, iid, 0)
        fun addCategory(builder: FlatBufferBuilder, category: Byte) = builder.addByte(1, category, 0)
        fun endImageQuery(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
