//! Stable system collection templates backing deterministic discovery shelves.
//!
//! These definitions bridge the current `/api/v1/discovery/*` shelves to the
//! dynamic collection substrate without changing the response shape. Each
//! definition carries the section metadata clients already consume plus the
//! dynamic rule, sort, limit, and shelf placement metadata needed to seed or
//! refresh a backing system collection.

use ferrex_model::{LibraryId, LibraryType};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::collections::{
    CollectionDuplicatePolicy, CollectionLimitPolicy, CollectionMediaKind,
    CollectionMediaScope, CollectionMemberAvailabilityStatus, CollectionOwner,
    CollectionOwnerType, CollectionPresentationMode, CollectionProvenance,
    CollectionRuleField, CollectionRuleOperator, CollectionRulePredicate,
    CollectionRuleValue, CollectionScope, CollectionSortDirection,
    CollectionSortField, CollectionSortKey, CollectionSortNulls,
    CollectionSortPolicy, CollectionSortTieBreaker, CollectionSource,
    CollectionVisibility, CollectionWatchProgressRuleValue,
    CollectionWatchStatus, CollectionWatchStatusRuleValue,
    DynamicCollectionRule, ShelfSurface,
};
use super::discovery::{
    DISCOVERY_SECTION_AUDIENCE_RATING_PICKS, DISCOVERY_SECTION_CONTINUE_SERIES,
    DISCOVERY_SECTION_RECENTLY_ADDED, DISCOVERY_SECTION_RECENTLY_RELEASED,
    DISCOVERY_SECTION_RESUME, DISCOVERY_SECTION_UNWATCHED_SERIES,
    DiscoveryItem, DiscoveryLayoutHint, DiscoverySection,
};

/// Upper bound used by system discovery definitions.
///
/// Discovery handlers may still apply a smaller request-scoped limit before
/// returning items. Keeping the seeded definition at the endpoint maximum lets
/// collection materialization remain reusable for all supported request limits.
pub const SYSTEM_DISCOVERY_COLLECTION_MAX_ITEMS: u32 = 40;
/// Stable placement group for home/explore discovery shelves.
pub const SYSTEM_DISCOVERY_HOME_SHELF_KEY: &str = "discovery:home";
/// Stable placement group for library-scoped discovery shelves.
pub const SYSTEM_DISCOVERY_LIBRARY_SHELF_KEY: &str = "discovery:library";
/// Provenance marker for definitions generated by the built-in discovery bridge.
pub const SYSTEM_DISCOVERY_GENERATOR: &str = "ferrex:system-discovery";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SystemDiscoveryShelf {
    Resume,
    RecentlyAddedMovies,
    RecentlyReleasedMovies,
    AudienceRatingPicks,
    ContinueSeries,
    UnwatchedSeries,
    RecentlyAddedSeries,
}

impl SystemDiscoveryShelf {
    pub const fn stable_suffix(self) -> &'static str {
        match self {
            Self::Resume => DISCOVERY_SECTION_RESUME,
            Self::RecentlyAddedMovies | Self::RecentlyAddedSeries => {
                DISCOVERY_SECTION_RECENTLY_ADDED
            }
            Self::RecentlyReleasedMovies => DISCOVERY_SECTION_RECENTLY_RELEASED,
            Self::AudienceRatingPicks => {
                DISCOVERY_SECTION_AUDIENCE_RATING_PICKS
            }
            Self::ContinueSeries => DISCOVERY_SECTION_CONTINUE_SERIES,
            Self::UnwatchedSeries => DISCOVERY_SECTION_UNWATCHED_SERIES,
        }
    }

    pub const fn section_id(self) -> &'static str {
        self.stable_suffix()
    }

    pub const fn title(self) -> &'static str {
        match self {
            Self::Resume => "Resume",
            Self::RecentlyAddedMovies | Self::RecentlyAddedSeries => {
                "Recently added"
            }
            Self::RecentlyReleasedMovies => "Recently released",
            Self::AudienceRatingPicks => "Audience rating picks",
            Self::ContinueSeries => "Continue series",
            Self::UnwatchedSeries => "Unwatched series",
        }
    }

    pub const fn reason(self) -> &'static str {
        match self {
            Self::Resume => "Pick up where you left off",
            Self::RecentlyAddedMovies => "New in your library",
            Self::RecentlyReleasedMovies => {
                "Recent releases available in your library"
            }
            Self::AudienceRatingPicks => "Highly rated titles with metadata",
            Self::ContinueSeries => "Resume an episode or play what is next",
            Self::UnwatchedSeries => {
                "Series you have not started in this library"
            }
            Self::RecentlyAddedSeries => "New series in this library",
        }
    }

    pub const fn layout_hint(self) -> DiscoveryLayoutHint {
        match self {
            Self::Resume | Self::ContinueSeries => {
                DiscoveryLayoutHint::ContinueRow
            }
            Self::RecentlyAddedMovies
            | Self::RecentlyReleasedMovies
            | Self::AudienceRatingPicks
            | Self::UnwatchedSeries
            | Self::RecentlyAddedSeries => DiscoveryLayoutHint::PosterRow,
        }
    }

    pub const fn placement_position(self) -> u32 {
        match self {
            Self::Resume | Self::ContinueSeries => 0,
            Self::RecentlyAddedMovies | Self::UnwatchedSeries => 10,
            Self::RecentlyReleasedMovies | Self::RecentlyAddedSeries => 20,
            Self::AudienceRatingPicks => 30,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SystemShelfPlacementScope {
    User {
        user_id: Uuid,
        library_id: Option<LibraryId>,
    },
}

impl SystemShelfPlacementScope {
    pub const fn placement_scope(&self) -> &'static str {
        match self {
            Self::User { .. } => "user",
        }
    }

    pub fn placement_scope_key(&self) -> String {
        match self {
            Self::User {
                user_id,
                library_id: Some(library_id),
            } => format!("user:{user_id}:library:{library_id}"),
            Self::User {
                user_id,
                library_id: None,
            } => format!("user:{user_id}"),
        }
    }

    pub const fn user_id(&self) -> Option<Uuid> {
        match self {
            Self::User { user_id, .. } => Some(*user_id),
        }
    }

    pub const fn library_id(&self) -> Option<LibraryId> {
        match self {
            Self::User { library_id, .. } => *library_id,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SystemShelfPlacementDefinition {
    pub surface: ShelfSurface,
    pub shelf_key: String,
    pub scope: SystemShelfPlacementScope,
    pub position: u32,
    pub pinned: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SystemCollectionDefinition {
    pub stable_key: String,
    pub shelf: SystemDiscoveryShelf,
    pub section_id: String,
    pub title: String,
    pub reason: Option<String>,
    pub layout_hint: DiscoveryLayoutHint,
    pub scope: CollectionScope,
    pub media_scope: CollectionMediaScope,
    pub rule: DynamicCollectionRule,
    pub placement: SystemShelfPlacementDefinition,
}

impl SystemCollectionDefinition {
    pub fn owner(&self) -> CollectionOwner {
        CollectionOwner {
            owner_type: CollectionOwnerType::System,
            user_id: None,
            device_id: None,
            display_name: Some("Ferrex".to_string()),
        }
    }

    pub const fn kind(&self) -> super::collections::CollectionKind {
        super::collections::CollectionKind::System
    }

    pub const fn source(&self) -> CollectionSource {
        CollectionSource::System
    }

    pub const fn visibility(&self) -> CollectionVisibility {
        CollectionVisibility::System
    }

    pub const fn presentation(&self) -> CollectionPresentationMode {
        CollectionPresentationMode::Shelf
    }

    pub const fn duplicate_policy(&self) -> CollectionDuplicatePolicy {
        CollectionDuplicatePolicy::DeduplicateMedia
    }

    pub fn description(&self) -> String {
        self.reason.clone().unwrap_or_else(|| self.title.clone())
    }

    pub fn provenance(&self) -> CollectionProvenance {
        CollectionProvenance {
            source: CollectionSource::System,
            external_id: Some(self.stable_key.clone()),
            generated_by: Some(SYSTEM_DISCOVERY_GENERATOR.to_string()),
            rule_hash: self.rule.rule_hash().ok(),
            ..CollectionProvenance::default()
        }
    }

    pub fn library_id(&self) -> Option<LibraryId> {
        match &self.media_scope {
            CollectionMediaScope::Library { library_id, .. } => {
                Some(*library_id)
            }
            _ => None,
        }
    }

    pub fn section(
        &self,
        items: Vec<DiscoveryItem>,
        requested_limit: usize,
    ) -> DiscoverySection {
        DiscoverySection::new(
            self.section_id.clone(),
            self.title.clone(),
            self.reason.clone(),
            self.layout_hint,
            items,
            requested_limit,
        )
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "snake_case")]
pub enum SystemCollectionStaleCause {
    Catalog,
    Metadata,
    WatchState,
    Rule,
}

impl SystemCollectionStaleCause {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Catalog => "catalog",
            Self::Metadata => "metadata",
            Self::WatchState => "watch_state",
            Self::Rule => "rule",
        }
    }

    pub const fn stale_reason(self) -> &'static str {
        match self {
            Self::Catalog => "system discovery catalog change",
            Self::Metadata => "system discovery metadata change",
            Self::WatchState => "system discovery watch-state change",
            Self::Rule => "system discovery rule change",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MarkSystemCollectionsStaleRequest {
    pub cause: SystemCollectionStaleCause,
    pub library_id: Option<LibraryId>,
    pub user_id: Option<Uuid>,
}

impl MarkSystemCollectionsStaleRequest {
    pub const fn catalog(library_id: Option<LibraryId>) -> Self {
        Self {
            cause: SystemCollectionStaleCause::Catalog,
            library_id,
            user_id: None,
        }
    }

    pub const fn metadata(library_id: Option<LibraryId>) -> Self {
        Self {
            cause: SystemCollectionStaleCause::Metadata,
            library_id,
            user_id: None,
        }
    }

    pub const fn watch_state(
        user_id: Uuid,
        library_id: Option<LibraryId>,
    ) -> Self {
        Self {
            cause: SystemCollectionStaleCause::WatchState,
            library_id,
            user_id: Some(user_id),
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct SystemCollectionSeedReport {
    pub requested: usize,
    pub upserted: usize,
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct SystemCollectionsStaleResponse {
    pub materializations_marked_stale: u64,
}

pub fn system_resume_collection(user_id: Uuid) -> SystemCollectionDefinition {
    system_definition(
        user_id,
        None,
        SystemDiscoveryShelf::Resume,
        CollectionScope::User,
        CollectionMediaScope::Types {
            media_types: vec![
                CollectionMediaKind::Movie,
                CollectionMediaKind::Episode,
            ],
        },
        all_rule(
            vec![
                media_types_predicate(vec![
                    CollectionMediaKind::Movie,
                    CollectionMediaKind::Episode,
                ]),
                availability_available_predicate(),
                watch_progress_predicate(user_id, Some(2), Some(94)),
            ],
            vec![
                sort_key_for_user(
                    CollectionSortField::LastWatchedAt,
                    CollectionSortDirection::Desc,
                    user_id,
                ),
                sort_key(
                    CollectionSortField::Title,
                    CollectionSortDirection::Asc,
                ),
            ],
            CollectionSortTieBreaker::StableMediaKey,
        ),
    )
}

pub fn system_global_explore_collections(
    user_id: Uuid,
) -> Vec<SystemCollectionDefinition> {
    vec![
        system_recently_added_movies_collection(user_id, None),
        system_recently_released_movies_collection(user_id, None),
        system_audience_rating_picks_collection(user_id, None),
    ]
}

pub fn system_library_discovery_collections(
    user_id: Uuid,
    library_id: LibraryId,
    library_type: LibraryType,
) -> Vec<SystemCollectionDefinition> {
    match library_type {
        LibraryType::Movies => vec![
            system_recently_added_movies_collection(user_id, Some(library_id)),
            system_recently_released_movies_collection(
                user_id,
                Some(library_id),
            ),
            system_audience_rating_picks_collection(user_id, Some(library_id)),
        ],
        LibraryType::Series => vec![
            system_continue_series_collection(user_id, library_id),
            system_unwatched_series_collection(user_id, library_id),
            system_recently_added_series_collection(user_id, library_id),
        ],
    }
}

fn system_recently_added_movies_collection(
    user_id: Uuid,
    library_id: Option<LibraryId>,
) -> SystemCollectionDefinition {
    let media_scope =
        scoped_media_scope(library_id, CollectionMediaKind::Movie);
    system_definition(
        user_id,
        library_id,
        SystemDiscoveryShelf::RecentlyAddedMovies,
        scope_for_library(library_id),
        media_scope,
        all_rule(
            movie_catalog_predicates(user_id, library_id),
            vec![
                sort_key(
                    CollectionSortField::RecentlyAdded,
                    CollectionSortDirection::Desc,
                ),
                sort_key(
                    CollectionSortField::Title,
                    CollectionSortDirection::Asc,
                ),
            ],
            CollectionSortTieBreaker::StableMediaKey,
        ),
    )
}

fn system_recently_released_movies_collection(
    user_id: Uuid,
    library_id: Option<LibraryId>,
) -> SystemCollectionDefinition {
    let mut predicates = movie_catalog_predicates(user_id, library_id);
    predicates.push(exists_predicate(CollectionRuleField::ReleaseDate));
    system_definition(
        user_id,
        library_id,
        SystemDiscoveryShelf::RecentlyReleasedMovies,
        scope_for_library(library_id),
        scoped_media_scope(library_id, CollectionMediaKind::Movie),
        all_rule(
            predicates,
            vec![
                sort_key(
                    CollectionSortField::RecentlyReleased,
                    CollectionSortDirection::Desc,
                ),
                sort_key(
                    CollectionSortField::Title,
                    CollectionSortDirection::Asc,
                ),
            ],
            CollectionSortTieBreaker::StableMediaKey,
        ),
    )
}

fn system_audience_rating_picks_collection(
    user_id: Uuid,
    library_id: Option<LibraryId>,
) -> SystemCollectionDefinition {
    let mut predicates = movie_catalog_predicates(user_id, library_id);
    predicates.push(exists_predicate(CollectionRuleField::Rating));
    system_definition(
        user_id,
        library_id,
        SystemDiscoveryShelf::AudienceRatingPicks,
        scope_for_library(library_id),
        scoped_media_scope(library_id, CollectionMediaKind::Movie),
        all_rule(
            predicates,
            vec![
                sort_key(
                    CollectionSortField::Rating,
                    CollectionSortDirection::Desc,
                ),
                sort_key(
                    CollectionSortField::Title,
                    CollectionSortDirection::Asc,
                ),
            ],
            CollectionSortTieBreaker::StableMediaKey,
        ),
    )
}

fn system_continue_series_collection(
    user_id: Uuid,
    library_id: LibraryId,
) -> SystemCollectionDefinition {
    system_definition(
        user_id,
        Some(library_id),
        SystemDiscoveryShelf::ContinueSeries,
        CollectionScope::Library,
        scoped_media_scope(Some(library_id), CollectionMediaKind::Series),
        all_rule(
            vec![
                media_type_predicate(CollectionMediaKind::Series),
                library_predicate(library_id),
                availability_available_predicate(),
                watch_status_predicate(
                    user_id,
                    CollectionRuleOperator::In,
                    vec![CollectionWatchStatus::InProgress],
                ),
            ],
            vec![
                sort_key_for_user(
                    CollectionSortField::LastWatchedAt,
                    CollectionSortDirection::Desc,
                    user_id,
                ),
                sort_key(
                    CollectionSortField::Title,
                    CollectionSortDirection::Asc,
                ),
            ],
            CollectionSortTieBreaker::StableMediaKey,
        ),
    )
}

fn system_unwatched_series_collection(
    user_id: Uuid,
    library_id: LibraryId,
) -> SystemCollectionDefinition {
    system_definition(
        user_id,
        Some(library_id),
        SystemDiscoveryShelf::UnwatchedSeries,
        CollectionScope::Library,
        scoped_media_scope(Some(library_id), CollectionMediaKind::Series),
        all_rule(
            vec![
                media_type_predicate(CollectionMediaKind::Series),
                library_predicate(library_id),
                availability_available_predicate(),
                watch_status_predicate(
                    user_id,
                    CollectionRuleOperator::Equals,
                    vec![CollectionWatchStatus::Unwatched],
                ),
            ],
            vec![
                sort_key(
                    CollectionSortField::RecentlyAdded,
                    CollectionSortDirection::Desc,
                ),
                sort_key(
                    CollectionSortField::Title,
                    CollectionSortDirection::Asc,
                ),
            ],
            CollectionSortTieBreaker::StableMediaKey,
        ),
    )
}

fn system_recently_added_series_collection(
    user_id: Uuid,
    library_id: LibraryId,
) -> SystemCollectionDefinition {
    system_definition(
        user_id,
        Some(library_id),
        SystemDiscoveryShelf::RecentlyAddedSeries,
        CollectionScope::Library,
        scoped_media_scope(Some(library_id), CollectionMediaKind::Series),
        all_rule(
            vec![
                media_type_predicate(CollectionMediaKind::Series),
                library_predicate(library_id),
                availability_available_predicate(),
            ],
            vec![
                sort_key(
                    CollectionSortField::RecentlyAdded,
                    CollectionSortDirection::Desc,
                ),
                sort_key(
                    CollectionSortField::Title,
                    CollectionSortDirection::Asc,
                ),
            ],
            CollectionSortTieBreaker::StableMediaKey,
        ),
    )
}

fn system_definition(
    user_id: Uuid,
    library_id: Option<LibraryId>,
    shelf: SystemDiscoveryShelf,
    scope: CollectionScope,
    media_scope: CollectionMediaScope,
    rule: DynamicCollectionRule,
) -> SystemCollectionDefinition {
    let stable_key = match library_id {
        Some(library_id) => format!(
            "system:discovery:user:{user_id}:library:{library_id}:{}",
            shelf.stable_suffix()
        ),
        None => {
            format!("system:discovery:user:{user_id}:{}", shelf.stable_suffix())
        }
    };
    let shelf_key = if library_id.is_some() {
        SYSTEM_DISCOVERY_LIBRARY_SHELF_KEY
    } else {
        SYSTEM_DISCOVERY_HOME_SHELF_KEY
    };

    SystemCollectionDefinition {
        stable_key,
        shelf,
        section_id: shelf.section_id().to_string(),
        title: shelf.title().to_string(),
        reason: Some(shelf.reason().to_string()),
        layout_hint: shelf.layout_hint(),
        scope,
        media_scope,
        rule,
        placement: SystemShelfPlacementDefinition {
            surface: if library_id.is_some() {
                ShelfSurface::Library
            } else {
                ShelfSurface::Home
            },
            shelf_key: shelf_key.to_string(),
            scope: SystemShelfPlacementScope::User {
                user_id,
                library_id,
            },
            position: shelf.placement_position(),
            pinned: true,
        },
    }
}

fn scope_for_library(library_id: Option<LibraryId>) -> CollectionScope {
    if library_id.is_some() {
        CollectionScope::Library
    } else {
        CollectionScope::User
    }
}

fn scoped_media_scope(
    library_id: Option<LibraryId>,
    media_type: CollectionMediaKind,
) -> CollectionMediaScope {
    match library_id {
        Some(library_id) => CollectionMediaScope::Library {
            library_id,
            media_types: vec![media_type],
        },
        None => CollectionMediaScope::Types {
            media_types: vec![media_type],
        },
    }
}

fn movie_catalog_predicates(
    user_id: Uuid,
    library_id: Option<LibraryId>,
) -> Vec<CollectionRulePredicate> {
    let mut predicates = vec![
        media_type_predicate(CollectionMediaKind::Movie),
        availability_available_predicate(),
        watch_status_predicate(
            user_id,
            CollectionRuleOperator::NotIn,
            vec![CollectionWatchStatus::Completed],
        ),
    ];
    if let Some(library_id) = library_id {
        predicates.push(library_predicate(library_id));
    }
    predicates
}

fn all_rule(
    predicates: Vec<CollectionRulePredicate>,
    sort_keys: Vec<CollectionSortKey>,
    tie_breaker: CollectionSortTieBreaker,
) -> DynamicCollectionRule {
    DynamicCollectionRule {
        predicate: CollectionRulePredicate::All {
            clauses: predicates,
        },
        sort: CollectionSortPolicy {
            keys: sort_keys,
            tie_breaker,
            ..CollectionSortPolicy::default()
        },
        limit: CollectionLimitPolicy {
            max_items: Some(SYSTEM_DISCOVERY_COLLECTION_MAX_ITEMS),
            ..CollectionLimitPolicy::default()
        },
        ..DynamicCollectionRule::default()
    }
}

fn media_type_predicate(
    media_type: CollectionMediaKind,
) -> CollectionRulePredicate {
    CollectionRulePredicate::Field {
        field: CollectionRuleField::MediaType,
        operator: CollectionRuleOperator::Equals,
        value: CollectionRuleValue::MediaType(media_type),
    }
}

fn media_types_predicate(
    media_types: Vec<CollectionMediaKind>,
) -> CollectionRulePredicate {
    CollectionRulePredicate::Field {
        field: CollectionRuleField::MediaType,
        operator: CollectionRuleOperator::In,
        value: CollectionRuleValue::MediaTypes(media_types),
    }
}

fn library_predicate(library_id: LibraryId) -> CollectionRulePredicate {
    CollectionRulePredicate::Field {
        field: CollectionRuleField::LibraryId,
        operator: CollectionRuleOperator::Equals,
        value: CollectionRuleValue::Uuid(library_id.to_uuid()),
    }
}

fn availability_available_predicate() -> CollectionRulePredicate {
    CollectionRulePredicate::Field {
        field: CollectionRuleField::Availability,
        operator: CollectionRuleOperator::Equals,
        value: CollectionRuleValue::Availability(
            CollectionMemberAvailabilityStatus::Available,
        ),
    }
}

fn watch_status_predicate(
    user_id: Uuid,
    operator: CollectionRuleOperator,
    statuses: Vec<CollectionWatchStatus>,
) -> CollectionRulePredicate {
    CollectionRulePredicate::Field {
        field: CollectionRuleField::WatchStatus,
        operator,
        value: CollectionRuleValue::WatchStatus(
            CollectionWatchStatusRuleValue { user_id, statuses },
        ),
    }
}

fn watch_progress_predicate(
    user_id: Uuid,
    min_percent: Option<u8>,
    max_percent: Option<u8>,
) -> CollectionRulePredicate {
    CollectionRulePredicate::Field {
        field: CollectionRuleField::WatchProgress,
        operator: CollectionRuleOperator::Between,
        value: CollectionRuleValue::WatchProgress(
            CollectionWatchProgressRuleValue {
                user_id,
                min_percent,
                max_percent,
            },
        ),
    }
}

fn exists_predicate(field: CollectionRuleField) -> CollectionRulePredicate {
    CollectionRulePredicate::Field {
        field,
        operator: CollectionRuleOperator::Exists,
        value: CollectionRuleValue::Boolean(true),
    }
}

fn sort_key(
    field: CollectionSortField,
    direction: CollectionSortDirection,
) -> CollectionSortKey {
    CollectionSortKey {
        field,
        direction,
        nulls: CollectionSortNulls::Last,
        user_id: None,
    }
}

fn sort_key_for_user(
    field: CollectionSortField,
    direction: CollectionSortDirection,
    user_id: Uuid,
) -> CollectionSortKey {
    CollectionSortKey {
        user_id: Some(user_id),
        ..sort_key(field, direction)
    }
}

#[cfg(test)]
mod tests {
    use ferrex_model::{LibraryId, LibraryType};

    use super::*;

    #[test]
    fn global_system_discovery_definitions_are_stable_and_valid() {
        let user_id = Uuid::from_u128(1);
        let first = system_global_explore_collections(user_id);
        let second = system_global_explore_collections(user_id);

        assert_eq!(first, second);
        assert_eq!(
            first
                .iter()
                .map(|definition| definition.section_id.as_str())
                .collect::<Vec<_>>(),
            vec![
                DISCOVERY_SECTION_RECENTLY_ADDED,
                DISCOVERY_SECTION_RECENTLY_RELEASED,
                DISCOVERY_SECTION_AUDIENCE_RATING_PICKS,
            ]
        );
        assert_eq!(
            first
                .iter()
                .map(|definition| definition.placement.position)
                .collect::<Vec<_>>(),
            vec![10, 20, 30]
        );
        assert!(first.iter().all(|definition| {
            definition
                .stable_key
                .starts_with(&format!("system:discovery:user:{user_id}:"))
                && definition.placement.surface == ShelfSurface::Home
                && definition.rule.limit.max_items
                    == Some(SYSTEM_DISCOVERY_COLLECTION_MAX_ITEMS)
                && definition.rule.validation_report().valid
        }));
    }

    #[test]
    fn library_system_discovery_definitions_scope_by_library_and_type() {
        let user_id = Uuid::from_u128(2);
        let library_id = LibraryId(Uuid::from_u128(3));
        let movie_definitions = system_library_discovery_collections(
            user_id,
            library_id,
            LibraryType::Movies,
        );
        let series_definitions = system_library_discovery_collections(
            user_id,
            library_id,
            LibraryType::Series,
        );

        assert_eq!(movie_definitions.len(), 3);
        assert_eq!(series_definitions.len(), 3);
        assert_eq!(
            series_definitions
                .iter()
                .map(|definition| definition.section_id.as_str())
                .collect::<Vec<_>>(),
            vec![
                DISCOVERY_SECTION_CONTINUE_SERIES,
                DISCOVERY_SECTION_UNWATCHED_SERIES,
                DISCOVERY_SECTION_RECENTLY_ADDED,
            ]
        );
        assert!(movie_definitions.iter().chain(&series_definitions).all(
            |definition| {
                definition.scope == CollectionScope::Library
                    && definition.library_id() == Some(library_id)
                    && definition.placement.surface == ShelfSurface::Library
                    && definition.placement.scope.placement_scope_key()
                        == format!("user:{user_id}:library:{library_id}")
                    && definition.rule.validation_report().valid
            }
        ));
    }

    #[test]
    fn definition_builds_discovery_section_with_existing_metadata() {
        let definition = system_resume_collection(Uuid::from_u128(4));
        let first_item = DiscoveryItem::new(
            ferrex_model::MediaID::Movie(ferrex_model::MovieID(
                Uuid::from_u128(5),
            )),
            "First",
        );
        let second_item = DiscoveryItem::new(
            ferrex_model::MediaID::Movie(ferrex_model::MovieID(
                Uuid::from_u128(6),
            )),
            "Second",
        );

        let section = definition.section(vec![first_item, second_item], 1);

        assert_eq!(section.id, DISCOVERY_SECTION_RESUME);
        assert_eq!(section.title, "Resume");
        assert_eq!(
            section.reason.as_deref(),
            Some("Pick up where you left off")
        );
        assert_eq!(section.layout_hint, DiscoveryLayoutHint::ContinueRow);
        assert_eq!(section.items.len(), 1);
    }
}
