// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.media

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EpisodeReference : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EpisodeReference {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val libraryId : ferrex.ids.Uuid get() = libraryId(ferrex.ids.Uuid())
    fun libraryId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field libraryId")
        }
    }
    val episodeNumber : UShort
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val seasonNumber : UShort
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val seasonId : ferrex.ids.Uuid get() = seasonId(ferrex.ids.Uuid())
    fun seasonId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field seasonId")
        }
    }
    val seriesId : ferrex.ids.Uuid get() = seriesId(ferrex.ids.Uuid())
    fun seriesId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field seriesId")
        }
    }
    val tmdbSeriesId : ULong
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val details : ferrex.details.EpisodeDetails? get() = details(ferrex.details.EpisodeDetails())
    fun details(obj: ferrex.details.EpisodeDetails) : ferrex.details.EpisodeDetails? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val endpoint : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val endpointAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(20, 1)
    fun endpointInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 20, 1)
    val file : ferrex.files.MediaFile? get() = file(ferrex.files.MediaFile())
    fun file(obj: ferrex.files.MediaFile) : ferrex.files.MediaFile? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val discoveredAt : ferrex.common.Timestamp? get() = discoveredAt(ferrex.common.Timestamp())
    fun discoveredAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(24)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val createdAt : ferrex.common.Timestamp? get() = createdAt(ferrex.common.Timestamp())
    fun createdAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(26)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsEpisodeReference(_bb: ByteBuffer): EpisodeReference = getRootAsEpisodeReference(_bb, EpisodeReference())
        fun getRootAsEpisodeReference(_bb: ByteBuffer, obj: EpisodeReference): EpisodeReference {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startEpisodeReference(builder: FlatBufferBuilder) = builder.startTable(12)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addLibraryId(builder: FlatBufferBuilder, libraryId: Int) = builder.addStruct(1, libraryId, 0)
        fun addEpisodeNumber(builder: FlatBufferBuilder, episodeNumber: UShort) = builder.addShort(2, episodeNumber.toShort(), 0)
        fun addSeasonNumber(builder: FlatBufferBuilder, seasonNumber: UShort) = builder.addShort(3, seasonNumber.toShort(), 0)
        fun addSeasonId(builder: FlatBufferBuilder, seasonId: Int) = builder.addStruct(4, seasonId, 0)
        fun addSeriesId(builder: FlatBufferBuilder, seriesId: Int) = builder.addStruct(5, seriesId, 0)
        fun addTmdbSeriesId(builder: FlatBufferBuilder, tmdbSeriesId: ULong) = builder.addLong(6, tmdbSeriesId.toLong(), 0)
        fun addDetails(builder: FlatBufferBuilder, details: Int) = builder.addOffset(7, details, 0)
        fun addEndpoint(builder: FlatBufferBuilder, endpoint: Int) = builder.addOffset(8, endpoint, 0)
        fun addFile(builder: FlatBufferBuilder, file: Int) = builder.addOffset(9, file, 0)
        fun addDiscoveredAt(builder: FlatBufferBuilder, discoveredAt: Int) = builder.addStruct(10, discoveredAt, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: Int) = builder.addStruct(11, createdAt, 0)
        fun endEpisodeReference(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 12)
                builder.required(o, 14)
            return o
        }
    }
}
