// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.media

@Suppress("unused")
class MediaVariant private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val MovieReference: UByte = 1u
        const val SeriesReference: UByte = 2u
        const val SeasonReference: UByte = 3u
        const val EpisodeReference: UByte = 4u
    }
}
