// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.media

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MovieReference : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MovieReference {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val libraryId : ferrex.ids.Uuid get() = libraryId(ferrex.ids.Uuid())
    fun libraryId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field libraryId")
        }
    }
    val batchId : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val tmdbId : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val title : String
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field title")
            }
        }
    val titleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun titleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val details : ferrex.details.EnhancedMovieDetails? get() = details(ferrex.details.EnhancedMovieDetails())
    fun details(obj: ferrex.details.EnhancedMovieDetails) : ferrex.details.EnhancedMovieDetails? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val endpoint : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val endpointAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(16, 1)
    fun endpointInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 16, 1)
    val file : ferrex.files.MediaFile? get() = file(ferrex.files.MediaFile())
    fun file(obj: ferrex.files.MediaFile) : ferrex.files.MediaFile? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val themeColor : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val themeColorAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(20, 1)
    fun themeColorInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 20, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMovieReference(_bb: ByteBuffer): MovieReference = getRootAsMovieReference(_bb, MovieReference())
        fun getRootAsMovieReference(_bb: ByteBuffer, obj: MovieReference): MovieReference {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startMovieReference(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addLibraryId(builder: FlatBufferBuilder, libraryId: Int) = builder.addStruct(1, libraryId, 0)
        fun addBatchId(builder: FlatBufferBuilder, batchId: UInt) = builder.addInt(2, batchId.toInt(), 0)
        fun addTmdbId(builder: FlatBufferBuilder, tmdbId: ULong) = builder.addLong(3, tmdbId.toLong(), 0)
        fun addTitle(builder: FlatBufferBuilder, title: Int) = builder.addOffset(4, title, 0)
        fun addDetails(builder: FlatBufferBuilder, details: Int) = builder.addOffset(5, details, 0)
        fun addEndpoint(builder: FlatBufferBuilder, endpoint: Int) = builder.addOffset(6, endpoint, 0)
        fun addFile(builder: FlatBufferBuilder, file: Int) = builder.addOffset(7, file, 0)
        fun addThemeColor(builder: FlatBufferBuilder, themeColor: Int) = builder.addOffset(8, themeColor, 0)
        fun endMovieReference(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 12)
            return o
        }
    }
}
