// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.media

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SeriesReference : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SeriesReference {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val libraryId : ferrex.ids.Uuid get() = libraryId(ferrex.ids.Uuid())
    fun libraryId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field libraryId")
        }
    }
    val tmdbId : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val title : String
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field title")
            }
        }
    val titleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun titleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    val details : ferrex.details.EnhancedSeriesDetails? get() = details(ferrex.details.EnhancedSeriesDetails())
    fun details(obj: ferrex.details.EnhancedSeriesDetails) : ferrex.details.EnhancedSeriesDetails? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val endpoint : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val endpointAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun endpointInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val discoveredAt : ferrex.common.Timestamp? get() = discoveredAt(ferrex.common.Timestamp())
    fun discoveredAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val createdAt : ferrex.common.Timestamp? get() = createdAt(ferrex.common.Timestamp())
    fun createdAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val themeColor : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val themeColorAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(20, 1)
    fun themeColorInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 20, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSeriesReference(_bb: ByteBuffer): SeriesReference = getRootAsSeriesReference(_bb, SeriesReference())
        fun getRootAsSeriesReference(_bb: ByteBuffer, obj: SeriesReference): SeriesReference {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startSeriesReference(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addLibraryId(builder: FlatBufferBuilder, libraryId: Int) = builder.addStruct(1, libraryId, 0)
        fun addTmdbId(builder: FlatBufferBuilder, tmdbId: ULong) = builder.addLong(2, tmdbId.toLong(), 0)
        fun addTitle(builder: FlatBufferBuilder, title: Int) = builder.addOffset(3, title, 0)
        fun addDetails(builder: FlatBufferBuilder, details: Int) = builder.addOffset(4, details, 0)
        fun addEndpoint(builder: FlatBufferBuilder, endpoint: Int) = builder.addOffset(5, endpoint, 0)
        fun addDiscoveredAt(builder: FlatBufferBuilder, discoveredAt: Int) = builder.addStruct(6, discoveredAt, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: Int) = builder.addStruct(7, createdAt, 0)
        fun addThemeColor(builder: FlatBufferBuilder, themeColor: Int) = builder.addOffset(8, themeColor, 0)
        fun endSeriesReference(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
                builder.required(o, 10)
            return o
        }
    }
}
