// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Cast credit metadata for detail pages and profile-image rails.
 */
@Suppress("unused")
class CastCredit : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CastCredit {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val creditId : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val creditIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun creditIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    val castId : ULong
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val name : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val originalName : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val originalNameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun originalNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val character : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val characterAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun characterInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val profile : ferrex.details.CreditProfile? get() = profile(ferrex.details.CreditProfile())
    fun profile(obj: ferrex.details.CreditProfile) : ferrex.details.CreditProfile? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val order : UInt
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val gender : UByte
        get() {
            val o = __offset(20)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val knownForDepartment : String?
        get() {
            val o = __offset(22)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val knownForDepartmentAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(22, 1)
    fun knownForDepartmentInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 22, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsCastCredit(_bb: ByteBuffer): CastCredit = getRootAsCastCredit(_bb, CastCredit())
        fun getRootAsCastCredit(_bb: ByteBuffer, obj: CastCredit): CastCredit {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCastCredit(builder: FlatBufferBuilder, id: ULong, creditIdOffset: Int, castId: ULong, nameOffset: Int, originalNameOffset: Int, characterOffset: Int, profileOffset: Int, order: UInt, gender: UByte, knownForDepartmentOffset: Int) : Int {
            builder.startTable(10)
            addCastId(builder, castId)
            addId(builder, id)
            addKnownForDepartment(builder, knownForDepartmentOffset)
            addOrder(builder, order)
            addProfile(builder, profileOffset)
            addCharacter(builder, characterOffset)
            addOriginalName(builder, originalNameOffset)
            addName(builder, nameOffset)
            addCreditId(builder, creditIdOffset)
            addGender(builder, gender)
            return endCastCredit(builder)
        }
        fun startCastCredit(builder: FlatBufferBuilder) = builder.startTable(10)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addCreditId(builder: FlatBufferBuilder, creditId: Int) = builder.addOffset(1, creditId, 0)
        fun addCastId(builder: FlatBufferBuilder, castId: ULong) = builder.addLong(2, castId.toLong(), 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(3, name, 0)
        fun addOriginalName(builder: FlatBufferBuilder, originalName: Int) = builder.addOffset(4, originalName, 0)
        fun addCharacter(builder: FlatBufferBuilder, character: Int) = builder.addOffset(5, character, 0)
        fun addProfile(builder: FlatBufferBuilder, profile: Int) = builder.addOffset(6, profile, 0)
        fun addOrder(builder: FlatBufferBuilder, order: UInt) = builder.addInt(7, order.toInt(), 0)
        fun addGender(builder: FlatBufferBuilder, gender: UByte) = builder.addByte(8, gender.toByte(), 0)
        fun addKnownForDepartment(builder: FlatBufferBuilder, knownForDepartment: Int) = builder.addOffset(9, knownForDepartment, 0)
        fun endCastCredit(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
