// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Person/profile metadata shared by cast and crew credits.
 */
@Suppress("unused")
class CreditProfile : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CreditProfile {
        __init(_i, _bb)
        return this
    }
    val personId : ferrex.ids.Uuid? get() = personId(ferrex.ids.Uuid())
    fun personId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val profilePath : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val profilePathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun profilePathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    val profileIid : ferrex.ids.Uuid? get() = profileIid(ferrex.ids.Uuid())
    fun profileIid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsCreditProfile(_bb: ByteBuffer): CreditProfile = getRootAsCreditProfile(_bb, CreditProfile())
        fun getRootAsCreditProfile(_bb: ByteBuffer, obj: CreditProfile): CreditProfile {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startCreditProfile(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addPersonId(builder: FlatBufferBuilder, personId: Int) = builder.addStruct(0, personId, 0)
        fun addProfilePath(builder: FlatBufferBuilder, profilePath: Int) = builder.addOffset(1, profilePath, 0)
        fun addProfileIid(builder: FlatBufferBuilder, profileIid: Int) = builder.addStruct(2, profileIid, 0)
        fun endCreditProfile(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
