// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Crew credit metadata for detail pages and profile-image rails.
 */
@Suppress("unused")
class CrewCredit : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : CrewCredit {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val creditId : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val creditIdAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun creditIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    val name : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    val job : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val jobAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun jobInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val department : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val departmentAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun departmentInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val profile : ferrex.details.CreditProfile? get() = profile(ferrex.details.CreditProfile())
    fun profile(obj: ferrex.details.CreditProfile) : ferrex.details.CreditProfile? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val gender : UByte
        get() {
            val o = __offset(16)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    val knownForDepartment : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val knownForDepartmentAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(18, 1)
    fun knownForDepartmentInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 18, 1)
    val originalName : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val originalNameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(20, 1)
    fun originalNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 20, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsCrewCredit(_bb: ByteBuffer): CrewCredit = getRootAsCrewCredit(_bb, CrewCredit())
        fun getRootAsCrewCredit(_bb: ByteBuffer, obj: CrewCredit): CrewCredit {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createCrewCredit(builder: FlatBufferBuilder, id: ULong, creditIdOffset: Int, nameOffset: Int, jobOffset: Int, departmentOffset: Int, profileOffset: Int, gender: UByte, knownForDepartmentOffset: Int, originalNameOffset: Int) : Int {
            builder.startTable(9)
            addId(builder, id)
            addOriginalName(builder, originalNameOffset)
            addKnownForDepartment(builder, knownForDepartmentOffset)
            addProfile(builder, profileOffset)
            addDepartment(builder, departmentOffset)
            addJob(builder, jobOffset)
            addName(builder, nameOffset)
            addCreditId(builder, creditIdOffset)
            addGender(builder, gender)
            return endCrewCredit(builder)
        }
        fun startCrewCredit(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addCreditId(builder: FlatBufferBuilder, creditId: Int) = builder.addOffset(1, creditId, 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(2, name, 0)
        fun addJob(builder: FlatBufferBuilder, job: Int) = builder.addOffset(3, job, 0)
        fun addDepartment(builder: FlatBufferBuilder, department: Int) = builder.addOffset(4, department, 0)
        fun addProfile(builder: FlatBufferBuilder, profile: Int) = builder.addOffset(5, profile, 0)
        fun addGender(builder: FlatBufferBuilder, gender: UByte) = builder.addByte(6, gender.toByte(), 0)
        fun addKnownForDepartment(builder: FlatBufferBuilder, knownForDepartment: Int) = builder.addOffset(7, knownForDepartment, 0)
        fun addOriginalName(builder: FlatBufferBuilder, originalName: Int) = builder.addOffset(8, originalName, 0)
        fun endCrewCredit(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
