// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EnhancedSeriesDetails : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EnhancedSeriesDetails {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val name : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    val originalName : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val originalNameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun originalNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    val overview : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val overviewAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun overviewInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val firstAirDate : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val firstAirDateAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun firstAirDateInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val lastAirDate : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val lastAirDateAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun lastAirDateInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val numberOfSeasons : UShort
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val numberOfEpisodes : UShort
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val availableSeasons : UShort
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val availableEpisodes : UShort
        get() {
            val o = __offset(22)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val voteAverage : Float
        get() {
            val o = __offset(24)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val voteCount : UInt
        get() {
            val o = __offset(26)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val popularity : Float
        get() {
            val o = __offset(28)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val contentRating : String?
        get() {
            val o = __offset(30)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val contentRatingAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(30, 1)
    fun contentRatingInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 30, 1)
    fun genres(j: Int) : ferrex.details.GenreInfo? = genres(ferrex.details.GenreInfo(), j)
    fun genres(obj: ferrex.details.GenreInfo, j: Int) : ferrex.details.GenreInfo? {
        val o = __offset(32)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val genresLength : Int
        get() {
            val o = __offset(32); return if (o != 0) __vector_len(o) else 0
        }
    val homepage : String?
        get() {
            val o = __offset(34)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val homepageAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(34, 1)
    fun homepageInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 34, 1)
    val status : String?
        get() {
            val o = __offset(36)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val statusAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(36, 1)
    fun statusInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 36, 1)
    val tagline : String?
        get() {
            val o = __offset(38)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val taglineAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(38, 1)
    fun taglineInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 38, 1)
    val inProduction : Boolean
        get() {
            val o = __offset(40)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    val posterPath : String?
        get() {
            val o = __offset(42)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val posterPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(42, 1)
    fun posterPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 42, 1)
    val backdropPath : String?
        get() {
            val o = __offset(44)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val backdropPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(44, 1)
    fun backdropPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 44, 1)
    val logoPath : String?
        get() {
            val o = __offset(46)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val logoPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(46, 1)
    fun logoPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 46, 1)
    val primaryPosterIid : ferrex.ids.Uuid? get() = primaryPosterIid(ferrex.ids.Uuid())
    fun primaryPosterIid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(48)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val primaryBackdropIid : ferrex.ids.Uuid? get() = primaryBackdropIid(ferrex.ids.Uuid())
    fun primaryBackdropIid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(50)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsEnhancedSeriesDetails(_bb: ByteBuffer): EnhancedSeriesDetails = getRootAsEnhancedSeriesDetails(_bb, EnhancedSeriesDetails())
        fun getRootAsEnhancedSeriesDetails(_bb: ByteBuffer, obj: EnhancedSeriesDetails): EnhancedSeriesDetails {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startEnhancedSeriesDetails(builder: FlatBufferBuilder) = builder.startTable(24)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(1, name, 0)
        fun addOriginalName(builder: FlatBufferBuilder, originalName: Int) = builder.addOffset(2, originalName, 0)
        fun addOverview(builder: FlatBufferBuilder, overview: Int) = builder.addOffset(3, overview, 0)
        fun addFirstAirDate(builder: FlatBufferBuilder, firstAirDate: Int) = builder.addOffset(4, firstAirDate, 0)
        fun addLastAirDate(builder: FlatBufferBuilder, lastAirDate: Int) = builder.addOffset(5, lastAirDate, 0)
        fun addNumberOfSeasons(builder: FlatBufferBuilder, numberOfSeasons: UShort) = builder.addShort(6, numberOfSeasons.toShort(), 0)
        fun addNumberOfEpisodes(builder: FlatBufferBuilder, numberOfEpisodes: UShort) = builder.addShort(7, numberOfEpisodes.toShort(), 0)
        fun addAvailableSeasons(builder: FlatBufferBuilder, availableSeasons: UShort) = builder.addShort(8, availableSeasons.toShort(), 0)
        fun addAvailableEpisodes(builder: FlatBufferBuilder, availableEpisodes: UShort) = builder.addShort(9, availableEpisodes.toShort(), 0)
        fun addVoteAverage(builder: FlatBufferBuilder, voteAverage: Float) = builder.addFloat(10, voteAverage, 0.0)
        fun addVoteCount(builder: FlatBufferBuilder, voteCount: UInt) = builder.addInt(11, voteCount.toInt(), 0)
        fun addPopularity(builder: FlatBufferBuilder, popularity: Float) = builder.addFloat(12, popularity, 0.0)
        fun addContentRating(builder: FlatBufferBuilder, contentRating: Int) = builder.addOffset(13, contentRating, 0)
        fun addGenres(builder: FlatBufferBuilder, genres: Int) = builder.addOffset(14, genres, 0)
        fun createGenresVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startGenresVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addHomepage(builder: FlatBufferBuilder, homepage: Int) = builder.addOffset(15, homepage, 0)
        fun addStatus(builder: FlatBufferBuilder, status: Int) = builder.addOffset(16, status, 0)
        fun addTagline(builder: FlatBufferBuilder, tagline: Int) = builder.addOffset(17, tagline, 0)
        fun addInProduction(builder: FlatBufferBuilder, inProduction: Boolean) = builder.addBoolean(18, inProduction, false)
        fun addPosterPath(builder: FlatBufferBuilder, posterPath: Int) = builder.addOffset(19, posterPath, 0)
        fun addBackdropPath(builder: FlatBufferBuilder, backdropPath: Int) = builder.addOffset(20, backdropPath, 0)
        fun addLogoPath(builder: FlatBufferBuilder, logoPath: Int) = builder.addOffset(21, logoPath, 0)
        fun addPrimaryPosterIid(builder: FlatBufferBuilder, primaryPosterIid: Int) = builder.addStruct(22, primaryPosterIid, 0)
        fun addPrimaryBackdropIid(builder: FlatBufferBuilder, primaryBackdropIid: Int) = builder.addStruct(23, primaryBackdropIid, 0)
        fun endEnhancedSeriesDetails(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
