// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EnhancedMovieDetails : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EnhancedMovieDetails {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val title : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val titleAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun titleInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    val originalTitle : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val originalTitleAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun originalTitleInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    val overview : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val overviewAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun overviewInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val releaseDate : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val releaseDateAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun releaseDateInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val runtime : UInt
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val voteAverage : Float
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val voteCount : UInt
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val popularity : Float
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val contentRating : String?
        get() {
            val o = __offset(22)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val contentRatingAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(22, 1)
    fun contentRatingInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 22, 1)
    fun genres(j: Int) : ferrex.details.GenreInfo? = genres(ferrex.details.GenreInfo(), j)
    fun genres(obj: ferrex.details.GenreInfo, j: Int) : ferrex.details.GenreInfo? {
        val o = __offset(24)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val genresLength : Int
        get() {
            val o = __offset(24); return if (o != 0) __vector_len(o) else 0
        }
    val homepage : String?
        get() {
            val o = __offset(26)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val homepageAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(26, 1)
    fun homepageInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 26, 1)
    val status : String?
        get() {
            val o = __offset(28)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val statusAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(28, 1)
    fun statusInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 28, 1)
    val tagline : String?
        get() {
            val o = __offset(30)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val taglineAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(30, 1)
    fun taglineInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 30, 1)
    val budget : ULong
        get() {
            val o = __offset(32)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val revenue : ULong
        get() {
            val o = __offset(34)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val posterPath : String?
        get() {
            val o = __offset(36)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val posterPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(36, 1)
    fun posterPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 36, 1)
    val backdropPath : String?
        get() {
            val o = __offset(38)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val backdropPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(38, 1)
    fun backdropPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 38, 1)
    val logoPath : String?
        get() {
            val o = __offset(40)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val logoPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(40, 1)
    fun logoPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 40, 1)
    val primaryPosterIid : ferrex.ids.Uuid? get() = primaryPosterIid(ferrex.ids.Uuid())
    fun primaryPosterIid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(42)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val primaryBackdropIid : ferrex.ids.Uuid? get() = primaryBackdropIid(ferrex.ids.Uuid())
    fun primaryBackdropIid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(44)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsEnhancedMovieDetails(_bb: ByteBuffer): EnhancedMovieDetails = getRootAsEnhancedMovieDetails(_bb, EnhancedMovieDetails())
        fun getRootAsEnhancedMovieDetails(_bb: ByteBuffer, obj: EnhancedMovieDetails): EnhancedMovieDetails {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startEnhancedMovieDetails(builder: FlatBufferBuilder) = builder.startTable(21)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addTitle(builder: FlatBufferBuilder, title: Int) = builder.addOffset(1, title, 0)
        fun addOriginalTitle(builder: FlatBufferBuilder, originalTitle: Int) = builder.addOffset(2, originalTitle, 0)
        fun addOverview(builder: FlatBufferBuilder, overview: Int) = builder.addOffset(3, overview, 0)
        fun addReleaseDate(builder: FlatBufferBuilder, releaseDate: Int) = builder.addOffset(4, releaseDate, 0)
        fun addRuntime(builder: FlatBufferBuilder, runtime: UInt) = builder.addInt(5, runtime.toInt(), 0)
        fun addVoteAverage(builder: FlatBufferBuilder, voteAverage: Float) = builder.addFloat(6, voteAverage, 0.0)
        fun addVoteCount(builder: FlatBufferBuilder, voteCount: UInt) = builder.addInt(7, voteCount.toInt(), 0)
        fun addPopularity(builder: FlatBufferBuilder, popularity: Float) = builder.addFloat(8, popularity, 0.0)
        fun addContentRating(builder: FlatBufferBuilder, contentRating: Int) = builder.addOffset(9, contentRating, 0)
        fun addGenres(builder: FlatBufferBuilder, genres: Int) = builder.addOffset(10, genres, 0)
        fun createGenresVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startGenresVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addHomepage(builder: FlatBufferBuilder, homepage: Int) = builder.addOffset(11, homepage, 0)
        fun addStatus(builder: FlatBufferBuilder, status: Int) = builder.addOffset(12, status, 0)
        fun addTagline(builder: FlatBufferBuilder, tagline: Int) = builder.addOffset(13, tagline, 0)
        fun addBudget(builder: FlatBufferBuilder, budget: ULong) = builder.addLong(14, budget.toLong(), 0)
        fun addRevenue(builder: FlatBufferBuilder, revenue: ULong) = builder.addLong(15, revenue.toLong(), 0)
        fun addPosterPath(builder: FlatBufferBuilder, posterPath: Int) = builder.addOffset(16, posterPath, 0)
        fun addBackdropPath(builder: FlatBufferBuilder, backdropPath: Int) = builder.addOffset(17, backdropPath, 0)
        fun addLogoPath(builder: FlatBufferBuilder, logoPath: Int) = builder.addOffset(18, logoPath, 0)
        fun addPrimaryPosterIid(builder: FlatBufferBuilder, primaryPosterIid: Int) = builder.addStruct(19, primaryPosterIid, 0)
        fun addPrimaryBackdropIid(builder: FlatBufferBuilder, primaryBackdropIid: Int) = builder.addStruct(20, primaryBackdropIid, 0)
        fun endEnhancedMovieDetails(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
