// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EpisodeDetails : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EpisodeDetails {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val episodeNumber : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val seasonNumber : UShort
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val name : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val overview : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val overviewAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun overviewInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val airDate : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val airDateAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun airDateInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val runtime : UInt
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val stillPath : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val stillPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(18, 1)
    fun stillPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 18, 1)
    val primaryStillIid : ferrex.ids.Uuid? get() = primaryStillIid(ferrex.ids.Uuid())
    fun primaryStillIid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val voteAverage : Float
        get() {
            val o = __offset(22)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.0f
        }
    val voteCount : UInt
        get() {
            val o = __offset(24)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val productionCode : String?
        get() {
            val o = __offset(26)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val productionCodeAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(26, 1)
    fun productionCodeInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 26, 1)
    fun guestStars(j: Int) : ferrex.details.CastCredit? = guestStars(ferrex.details.CastCredit(), j)
    fun guestStars(obj: ferrex.details.CastCredit, j: Int) : ferrex.details.CastCredit? {
        val o = __offset(28)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val guestStarsLength : Int
        get() {
            val o = __offset(28); return if (o != 0) __vector_len(o) else 0
        }
    fun crew(j: Int) : ferrex.details.CrewCredit? = crew(ferrex.details.CrewCredit(), j)
    fun crew(obj: ferrex.details.CrewCredit, j: Int) : ferrex.details.CrewCredit? {
        val o = __offset(30)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val crewLength : Int
        get() {
            val o = __offset(30); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsEpisodeDetails(_bb: ByteBuffer): EpisodeDetails = getRootAsEpisodeDetails(_bb, EpisodeDetails())
        fun getRootAsEpisodeDetails(_bb: ByteBuffer, obj: EpisodeDetails): EpisodeDetails {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startEpisodeDetails(builder: FlatBufferBuilder) = builder.startTable(14)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addEpisodeNumber(builder: FlatBufferBuilder, episodeNumber: UShort) = builder.addShort(1, episodeNumber.toShort(), 0)
        fun addSeasonNumber(builder: FlatBufferBuilder, seasonNumber: UShort) = builder.addShort(2, seasonNumber.toShort(), 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(3, name, 0)
        fun addOverview(builder: FlatBufferBuilder, overview: Int) = builder.addOffset(4, overview, 0)
        fun addAirDate(builder: FlatBufferBuilder, airDate: Int) = builder.addOffset(5, airDate, 0)
        fun addRuntime(builder: FlatBufferBuilder, runtime: UInt) = builder.addInt(6, runtime.toInt(), 0)
        fun addStillPath(builder: FlatBufferBuilder, stillPath: Int) = builder.addOffset(7, stillPath, 0)
        fun addPrimaryStillIid(builder: FlatBufferBuilder, primaryStillIid: Int) = builder.addStruct(8, primaryStillIid, 0)
        fun addVoteAverage(builder: FlatBufferBuilder, voteAverage: Float) = builder.addFloat(9, voteAverage, 0.0)
        fun addVoteCount(builder: FlatBufferBuilder, voteCount: UInt) = builder.addInt(10, voteCount.toInt(), 0)
        fun addProductionCode(builder: FlatBufferBuilder, productionCode: Int) = builder.addOffset(11, productionCode, 0)
        fun addGuestStars(builder: FlatBufferBuilder, guestStars: Int) = builder.addOffset(12, guestStars, 0)
        fun createGuestStarsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startGuestStarsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addCrew(builder: FlatBufferBuilder, crew: Int) = builder.addOffset(13, crew, 0)
        fun createCrewVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startCrewVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endEpisodeDetails(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
