// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Related TMDB media reference used by recommendations/similar rails.
 */
@Suppress("unused")
class RelatedMediaRef : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : RelatedMediaRef {
        __init(_i, _bb)
        return this
    }
    val tmdbId : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val title : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val titleAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(6, 1)
    fun titleInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 6, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsRelatedMediaRef(_bb: ByteBuffer): RelatedMediaRef = getRootAsRelatedMediaRef(_bb, RelatedMediaRef())
        fun getRootAsRelatedMediaRef(_bb: ByteBuffer, obj: RelatedMediaRef): RelatedMediaRef {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createRelatedMediaRef(builder: FlatBufferBuilder, tmdbId: ULong, titleOffset: Int) : Int {
            builder.startTable(2)
            addTmdbId(builder, tmdbId)
            addTitle(builder, titleOffset)
            return endRelatedMediaRef(builder)
        }
        fun startRelatedMediaRef(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addTmdbId(builder: FlatBufferBuilder, tmdbId: ULong) = builder.addLong(0, tmdbId.toLong(), 0)
        fun addTitle(builder: FlatBufferBuilder, title: Int) = builder.addOffset(1, title, 0)
        fun endRelatedMediaRef(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
