// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.details

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class SeasonDetails : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SeasonDetails {
        __init(_i, _bb)
        return this
    }
    val id : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val seasonNumber : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val name : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    val overview : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val overviewAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun overviewInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val airDate : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val airDateAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun airDateInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val episodeCount : UShort
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val posterPath : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val posterPathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(16, 1)
    fun posterPathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 16, 1)
    val primaryPosterIid : ferrex.ids.Uuid? get() = primaryPosterIid(ferrex.ids.Uuid())
    fun primaryPosterIid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val runtime : UInt
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSeasonDetails(_bb: ByteBuffer): SeasonDetails = getRootAsSeasonDetails(_bb, SeasonDetails())
        fun getRootAsSeasonDetails(_bb: ByteBuffer, obj: SeasonDetails): SeasonDetails {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startSeasonDetails(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addId(builder: FlatBufferBuilder, id: ULong) = builder.addLong(0, id.toLong(), 0)
        fun addSeasonNumber(builder: FlatBufferBuilder, seasonNumber: UShort) = builder.addShort(1, seasonNumber.toShort(), 0)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(2, name, 0)
        fun addOverview(builder: FlatBufferBuilder, overview: Int) = builder.addOffset(3, overview, 0)
        fun addAirDate(builder: FlatBufferBuilder, airDate: Int) = builder.addOffset(4, airDate, 0)
        fun addEpisodeCount(builder: FlatBufferBuilder, episodeCount: UShort) = builder.addShort(5, episodeCount.toShort(), 0)
        fun addPosterPath(builder: FlatBufferBuilder, posterPath: Int) = builder.addOffset(6, posterPath, 0)
        fun addPrimaryPosterIid(builder: FlatBufferBuilder, primaryPosterIid: Int) = builder.addStruct(7, primaryPosterIid, 0)
        fun addRuntime(builder: FlatBufferBuilder, runtime: UInt) = builder.addInt(8, runtime.toInt(), 0)
        fun endSeasonDetails(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
