#!/usr/bin/env bash
# Generate Rust FlatBuffers types from .fbs schemas.
# Output: ferrex-flatbuffers/src/generated/
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_DIR="$SCRIPT_DIR/../schemas"
OUT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)/ferrex-flatbuffers/src/generated"

# Ensure flatc is available
if ! command -v flatc &>/dev/null; then
  echo "ERROR: flatc not found in PATH."
  echo "Install via: nix-shell -p flatbuffers, or download from"
  echo "https://github.com/google/flatbuffers/releases"
  exit 1
fi

echo "flatc version: $(flatc --version)"
echo "Schemas:       $SCHEMA_DIR"
echo "Output:        $OUT_DIR"

mkdir -p "$OUT_DIR"

# Generate Rust code for all schemas.
flatc --rust \
  -o "$OUT_DIR" \
  -I "$SCHEMA_DIR" \
  --gen-all \
  "$SCHEMA_DIR/ids.fbs" \
  "$SCHEMA_DIR/common.fbs" \
  "$SCHEMA_DIR/files.fbs" \
  "$SCHEMA_DIR/details.fbs" \
  "$SCHEMA_DIR/media.fbs" \
  "$SCHEMA_DIR/library.fbs" \
  "$SCHEMA_DIR/watch.fbs" \
  "$SCHEMA_DIR/auth.fbs" \
  "$SCHEMA_DIR/image.fbs"

# flatc --rust-module-root-file produces an incomplete mod.rs when
# multiple schema files are compiled together. Generate a correct one
# by scanning all _generated.rs files per namespace directory.
generate_module() {
  local dir="$1"
  local namespace
  namespace=$(basename "$dir")
  echo "  pub mod $namespace {"
  echo "    use super::*;"
  for f in "$dir"/*_generated.rs; do
    [ -f "$f" ] || continue
    local modname
    modname=$(basename "$f" .rs)
    echo "    mod $modname;"
    echo "    pub use self::${modname}::*;"
  done
  echo "  } // $namespace"
}

{
  echo "// Automatically generated by generate-rust.sh — do not edit."
  echo "// @generated"
  echo "pub mod ferrex {"
  echo "  use super::*;"
  for ns_dir in "$OUT_DIR"/ferrex/*/; do
    [ -d "$ns_dir" ] || continue
    generate_module "$ns_dir"
  done
  echo "} // ferrex"
} > "$OUT_DIR/mod.rs"

echo "✓ Rust FlatBuffers code generated in $OUT_DIR"
