#!/usr/bin/env bash
# Generate Rust FlatBuffers bindings from the shared mobile schemas.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCHEMA_DIR="$SCRIPT_DIR/../schemas"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
OUT_DIR="$REPO_ROOT/crates/ferrex-flatbuffers/src/generated"

if ! command -v flatc >/dev/null 2>&1; then
  echo "ERROR: flatc not found in PATH." >&2
  echo "Run with: nix shell nixpkgs#flatbuffers -c $0" >&2
  exit 1
fi

schemas=(
  "$SCHEMA_DIR/ids.fbs"
  "$SCHEMA_DIR/common.fbs"
  "$SCHEMA_DIR/files.fbs"
  "$SCHEMA_DIR/details.fbs"
  "$SCHEMA_DIR/media.fbs"
  "$SCHEMA_DIR/library.fbs"
  "$SCHEMA_DIR/auth.fbs"
  "$SCHEMA_DIR/image.fbs"
)

echo "flatc version: $(flatc --version)"
echo "Schemas:       $SCHEMA_DIR"
echo "Output:        $OUT_DIR"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

flatc --rust \
  --rust-module-root-file \
  -o "$OUT_DIR" \
  -I "$SCHEMA_DIR" \
  --gen-all \
  "${schemas[@]}"

# flatc's --rust-module-root-file root omits namespaces unless they are directly
# reachable from the final schema's root type. Generate a deterministic complete
# root module by scanning the namespace directories instead.
generate_namespace_module() {
  local dir="$1"
  local namespace
  namespace="$(basename "$dir")"
  echo "  pub mod $namespace {"
  echo "    use super::*;"
  find "$dir" -maxdepth 1 -type f -name '*_generated.rs' \
    -printf '%f\n' | sort | while read -r filename; do
      local modname="${filename%.rs}"
      echo "    mod $modname;"
      echo "    pub use self::${modname}::*;"
    done
  echo "  }"
}

{
  echo "// Automatically generated by mobile/shared/codegen/generate-rust.sh; do not edit."
  echo "// @generated"
  echo "pub mod ferrex {"
  echo "  use super::*;"
  find "$OUT_DIR/ferrex" -mindepth 1 -maxdepth 1 -type d \
    -printf '%p\n' | sort | while read -r ns_dir; do
      generate_namespace_module "$ns_dir"
    done
  echo "}"
} >"$OUT_DIR/mod.rs"

if command -v rustfmt >/dev/null 2>&1; then
  find "$OUT_DIR" -type f -name '*.rs' -print0 | xargs -0 rustfmt
else
  echo "WARNING: rustfmt not found; generated Rust was not formatted." >&2
fi

echo "✓ Rust FlatBuffers code generated in $OUT_DIR"
