// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.ids

@Suppress("unused")
class MediaIdVariant private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val MovieId: UByte = 1u
        const val SeriesId: UByte = 2u
        const val SeasonId: UByte = 3u
        const val EpisodeId: UByte = 4u
    }
}
