// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.ids

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

/**
 * Fixed-size UUID stored as 16 raw bytes.
 */
@Suppress("unused")
class Uuid : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Uuid {
        __init(_i, _bb)
        return this
    }
    val b0 : UByte get() = bb.get(bb_pos + 0).toUByte()
    val b1 : UByte get() = bb.get(bb_pos + 1).toUByte()
    val b2 : UByte get() = bb.get(bb_pos + 2).toUByte()
    val b3 : UByte get() = bb.get(bb_pos + 3).toUByte()
    val b4 : UByte get() = bb.get(bb_pos + 4).toUByte()
    val b5 : UByte get() = bb.get(bb_pos + 5).toUByte()
    val b6 : UByte get() = bb.get(bb_pos + 6).toUByte()
    val b7 : UByte get() = bb.get(bb_pos + 7).toUByte()
    val b8 : UByte get() = bb.get(bb_pos + 8).toUByte()
    val b9 : UByte get() = bb.get(bb_pos + 9).toUByte()
    val b10 : UByte get() = bb.get(bb_pos + 10).toUByte()
    val b11 : UByte get() = bb.get(bb_pos + 11).toUByte()
    val b12 : UByte get() = bb.get(bb_pos + 12).toUByte()
    val b13 : UByte get() = bb.get(bb_pos + 13).toUByte()
    val b14 : UByte get() = bb.get(bb_pos + 14).toUByte()
    val b15 : UByte get() = bb.get(bb_pos + 15).toUByte()
    companion object {
        fun createUuid(builder: FlatBufferBuilder, b0: UByte, b1: UByte, b2: UByte, b3: UByte, b4: UByte, b5: UByte, b6: UByte, b7: UByte, b8: UByte, b9: UByte, b10: UByte, b11: UByte, b12: UByte, b13: UByte, b14: UByte, b15: UByte) : Int {
            builder.prep(1, 16)
            builder.putByte(b15.toByte())
            builder.putByte(b14.toByte())
            builder.putByte(b13.toByte())
            builder.putByte(b12.toByte())
            builder.putByte(b11.toByte())
            builder.putByte(b10.toByte())
            builder.putByte(b9.toByte())
            builder.putByte(b8.toByte())
            builder.putByte(b7.toByte())
            builder.putByte(b6.toByte())
            builder.putByte(b5.toByte())
            builder.putByte(b4.toByte())
            builder.putByte(b3.toByte())
            builder.putByte(b2.toByte())
            builder.putByte(b1.toByte())
            builder.putByte(b0.toByte())
            return builder.offset()
        }
    }
}
