#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'

fail() {
	printf 'error: %s\n' "$*" >&2
	exit 1
}

info() {
	printf '%s\n' "$*" >&2
}

usage() {
	cat <<'USAGE'
Disposable per-worktree PostgreSQL for Ferrex SQLx workflows.

Usage:
  scripts/dev/sqlx-db.sh <command> [args]

Commands:
  start          initialize or start this worktree's local PostgreSQL cluster
  status         show whether the cluster is running and where its state lives
  migrate        start the cluster and run Ferrex migrations against it
  prepare        start, migrate, and run cargo sqlx prepare
  prepare-check  run the SQLx offline prepare check without connecting to a DB
  stop           stop the cluster, leaving data and .env.sqlx in place
  reset          stop, delete cluster data, recreate, and run migrations
  destroy        stop and delete cluster data plus the generated env file
  env            print the generated env file path
  psql           open psql on the app database (use --admin for admin role)
  help           show this help

The workflow never reads .env and always generates local Unix-socket URLs in
.env.sqlx. It refuses non-local/prod-looking ambient DATABASE_URL values before
running commands that touch the live database.
USAGE
}

require_command() {
	local cmd="$1"
	command -v "$cmd" >/dev/null 2>&1 || fail "required command not found: $cmd (enter nix develop .#server or .#ferrex-player)"
}

find_workspace_root() {
	local dir
	dir="$(pwd -P)"

	while [[ "$dir" != "/" ]]; do
		if [[ -f "$dir/Cargo.toml" && -f "$dir/flake.nix" && -d "$dir/crates/ferrex-core/migrations" ]]; then
			printf '%s\n' "$dir"
			return 0
		fi
		dir="$(dirname "$dir")"
	done

	fail "could not find Ferrex workspace root from $(pwd -P)"
}

ROOT="${FERREX_WORKSPACE_ROOT:-$(find_workspace_root)}"
WORKTREE_KEY="$(printf '%s' "$ROOT" | sha256sum | awk '{print substr($1, 1, 16)}')"
STATE_BASE="${FERREX_SQLX_DB_STATE_BASE:-${XDG_STATE_HOME:-$HOME/.local/state}/ferrex/sqlx-db}"
STATE_DIR="${FERREX_SQLX_DB_STATE_DIR:-$STATE_BASE/$WORKTREE_KEY}"
DATA_DIR="$STATE_DIR/data"
RUN_DIR="$STATE_DIR/run"
SOCKET_DIR="$RUN_DIR/socket"
LOG_DIR="$STATE_DIR/log"
LOG_FILE="$LOG_DIR/postgres.log"
MARKER_FILE="$STATE_DIR/.ferrex-sqlx-db-state"
PGPASSFILE_PATH="$STATE_DIR/pgpass-empty"
ENV_FILE="${FERREX_SQLX_DB_ENV_FILE:-$ROOT/.env.sqlx}"
PORT="${FERREX_SQLX_DB_PORT:-5432}"
DB_NAME="${FERREX_SQLX_DB_NAME:-ferrex}"
ADMIN_USER="${FERREX_SQLX_DB_ADMIN_USER:-postgres}"
APP_USER="${FERREX_SQLX_DB_APP_USER:-ferrex_app}"
MIGRATIONS_DIR="$ROOT/crates/ferrex-core/migrations"

require_identifier() {
	local label="$1"
	local value="$2"
	[[ "$value" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || fail "$label must be a simple PostgreSQL identifier"
}

validate_config() {
	require_identifier "FERREX_SQLX_DB_NAME" "$DB_NAME"
	require_identifier "FERREX_SQLX_DB_ADMIN_USER" "$ADMIN_USER"
	require_identifier "FERREX_SQLX_DB_APP_USER" "$APP_USER"
	[[ "$PORT" =~ ^[0-9]+$ ]] || fail "FERREX_SQLX_DB_PORT must be numeric"
	((PORT >= 1 && PORT <= 65535)) || fail "FERREX_SQLX_DB_PORT must be between 1 and 65535"
}

quote_ident() {
	local value="$1"
	printf '"%s"' "$value"
}

sql_literal() {
	local value="$1"
	printf "'%s'" "$value"
}

urlencode() {
	require_command python3
	python3 - "$1" <<'PY'
import sys
from urllib.parse import quote
print(quote(sys.argv[1], safe=""))
PY
}

database_url_for_user() {
	local user="$1"
	local encoded_socket
	encoded_socket="$(urlencode "$SOCKET_DIR")"
	printf 'postgresql:///?host=%s&port=%s&user=%s&dbname=%s&sslmode=disable' \
		"$encoded_socket" "$PORT" "$user" "$DB_NAME"
}

write_export() {
	local key="$1"
	local value="$2"
	printf 'export %s=%q\n' "$key" "$value"
}

ensure_layout() {
	umask 077
	mkdir -p "$STATE_DIR" "$DATA_DIR" "$RUN_DIR" "$SOCKET_DIR" "$LOG_DIR"
	chmod 700 "$STATE_DIR" "$DATA_DIR" "$RUN_DIR" "$SOCKET_DIR" "$LOG_DIR"
	: >"$PGPASSFILE_PATH"
	chmod 600 "$PGPASSFILE_PATH"
	printf 'root=%s\nstate=%s\n' "$ROOT" "$STATE_DIR" >"$MARKER_FILE"
	chmod 600 "$MARKER_FILE"
}

write_env_file() {
	ensure_layout

	local app_url admin_url tmp
	app_url="$(database_url_for_user "$APP_USER")"
	admin_url="$(database_url_for_user "$ADMIN_USER")"
	tmp="$ENV_FILE.tmp"

	umask 077
	{
		printf '# Generated by scripts/dev/sqlx-db.sh; safe local-only SQLx PostgreSQL env.\n'
		printf '# Do not edit by hand; rerun scripts/dev/sqlx-db.sh start.\n'
		write_export FERREX_SQLX_DB_STATE_DIR "$STATE_DIR"
		write_export PGHOST "$SOCKET_DIR"
		write_export PGPORT "$PORT"
		write_export PGDATABASE "$DB_NAME"
		write_export PGUSER "$APP_USER"
		write_export PGSSLMODE disable
		write_export PGPASSFILE "$PGPASSFILE_PATH"
		write_export DATABASE_URL "$app_url"
		write_export DATABASE_URL_ADMIN "$admin_url"
		write_export SQLX_OFFLINE false
	} >"$tmp"
	mv "$tmp" "$ENV_FILE"
	chmod 600 "$ENV_FILE"
}

export_local_env() {
	ensure_layout

	local app_url admin_url
	app_url="$(database_url_for_user "$APP_USER")"
	admin_url="$(database_url_for_user "$ADMIN_USER")"

	unset PGPASSWORD DATABASE_PASSWORD DATABASE_ADMIN_PASSWORD DATABASE_URL_FILE DATABASE_PASSWORD_FILE
	export FERREX_SQLX_DB_STATE_DIR="$STATE_DIR"
	export PGHOST="$SOCKET_DIR"
	export PGPORT="$PORT"
	export PGDATABASE="$DB_NAME"
	export PGUSER="$APP_USER"
	export PGSSLMODE=disable
	export PGPASSFILE="$PGPASSFILE_PATH"
	export DATABASE_URL="$app_url"
	export DATABASE_URL_ADMIN="$admin_url"
	export SQLX_OFFLINE=false

	validate_local_url DATABASE_URL "$DATABASE_URL" "$APP_USER"
	validate_local_url DATABASE_URL_ADMIN "$DATABASE_URL_ADMIN" "$ADMIN_USER"
	write_env_file
}

validate_local_url() {
	local name="$1"
	local value="$2"
	local expected_user="$3"

	require_command python3
	URL_NAME="$name" \
		URL_VALUE="$value" \
		EXPECTED_SOCKET_DIR="$SOCKET_DIR" \
		EXPECTED_PORT="$PORT" \
		EXPECTED_DB="$DB_NAME" \
		EXPECTED_USER="$expected_user" \
		python3 - <<'PY'
import os
import sys
from urllib.parse import parse_qs, unquote, urlparse

name = os.environ["URL_NAME"]
value = os.environ["URL_VALUE"]
expected_socket = os.environ["EXPECTED_SOCKET_DIR"]
expected_port = os.environ["EXPECTED_PORT"]
expected_db = os.environ["EXPECTED_DB"]
expected_user = os.environ["EXPECTED_USER"]

parsed = urlparse(value)
if parsed.scheme not in {"postgres", "postgresql"}:
    sys.exit(f"{name} must use a PostgreSQL URL scheme")
if parsed.password is not None or "password=" in parsed.query.lower():
    sys.exit(f"{name} must not contain a password")

query = {key: values[-1] for key, values in parse_qs(parsed.query, keep_blank_values=True).items()}
host = query.get("host") or (unquote(parsed.hostname) if parsed.hostname else "")
user = query.get("user") or (unquote(parsed.username) if parsed.username else "")
db = query.get("dbname") or parsed.path.lstrip("/")
port = str(query.get("port") or (parsed.port if parsed.port is not None else "5432"))
sslmode = query.get("sslmode", "")

if host != expected_socket or not host.startswith("/"):
    sys.exit(f"{name} must target this worktree's Unix socket")
if port != expected_port:
    sys.exit(f"{name} must target this worktree's PostgreSQL port")
if db != expected_db:
    sys.exit(f"{name} must target this worktree's disposable database")
if user != expected_user:
    sys.exit(f"{name} must use the expected disposable role")
if sslmode and sslmode != "disable":
    sys.exit(f"{name} must disable SSL for Unix-socket access")
PY
}

check_ambient_url() {
	local name="$1"
	local value="${!name:-}"
	[[ -z "$value" ]] && return 0

	require_command python3
	if ! URL_NAME="$name" URL_VALUE="$value" python3 - <<'PY'; then
import os
import sys
from urllib.parse import parse_qs, unquote, urlparse

name = os.environ["URL_NAME"]
value = os.environ["URL_VALUE"]
prod_markers = (
    "prod",
    "production",
    "rds.amazonaws",
    "neon.tech",
    "supabase",
    "railway",
    "render.com",
    "fly.dev",
    "digitalocean",
)
try:
    parsed = urlparse(value)
except Exception:
    sys.exit(1)

text = value.lower()
if any(marker in text for marker in prod_markers):
    sys.exit(1)

query = {key: values[-1] for key, values in parse_qs(parsed.query, keep_blank_values=True).items()}
host = query.get("host") or (unquote(parsed.hostname) if parsed.hostname else "")
local_hosts = {"", "localhost", "127.0.0.1", "::1"}
if host.startswith("/") or host in local_hosts:
    sys.exit(0)

sys.exit(1)
PY
		fail "$name is set to a non-local/prod-looking URL; refusing to touch SQLx database state. Unset it or use the generated .env.sqlx."
	fi
}

check_ambient_urls() {
	check_ambient_url DATABASE_URL
	check_ambient_url DATABASE_URL_ADMIN
}

require_pg_commands() {
	require_command initdb
	require_command pg_ctl
	require_command psql
	require_command createdb
}

require_sqlx_cli() {
	require_command cargo
	command -v cargo-sqlx >/dev/null 2>&1 || command -v sqlx >/dev/null 2>&1 || fail "sqlx-cli not found (cargo sqlx/cargo-sqlx); enter nix develop .#server or .#ferrex-player"
}

pg_is_running() {
	[[ -d "$DATA_DIR" ]] || return 1
	pg_ctl -D "$DATA_DIR" status >/dev/null 2>&1
}

cleanup_stale_runtime() {
	[[ -d "$DATA_DIR" ]] || return 0
	if pg_is_running; then
		return 0
	fi

	rm -f "$SOCKET_DIR/.s.PGSQL.$PORT" "$SOCKET_DIR/.s.PGSQL.$PORT.lock"
	if [[ -f "$DATA_DIR/postmaster.pid" ]]; then
		rm -f "$DATA_DIR/postmaster.pid"
	fi
}

append_postgres_config() {
	local escaped_socket
	escaped_socket="${SOCKET_DIR//\'/\'\'}"
	cat >>"$DATA_DIR/postgresql.conf" <<EOF

# Ferrex disposable SQLx worktree cluster
listen_addresses = ''
port = $PORT
unix_socket_directories = '$escaped_socket'
unix_socket_permissions = 0700
log_statement = 'none'
log_connections = off
log_disconnections = off
fsync = off
synchronous_commit = off
full_page_writes = off
EOF

	cat >"$DATA_DIR/pg_hba.conf" <<EOF
# Ferrex disposable SQLx worktree cluster: local Unix socket only, no passwords.
local all all trust
host all all 127.0.0.1/32 reject
host all all ::1/128 reject
EOF
}

init_cluster_if_needed() {
	if [[ -s "$DATA_DIR/PG_VERSION" ]]; then
		return 0
	fi

	info "initializing disposable PostgreSQL cluster for this worktree"
	rm -rf "$DATA_DIR"
	mkdir -p "$DATA_DIR"
	chmod 700 "$DATA_DIR"
	initdb -D "$DATA_DIR" -U "$ADMIN_USER" -A trust --no-locale --encoding=UTF8 >"$LOG_DIR/initdb.log"
	append_postgres_config
}

start_postgres() {
	require_pg_commands
	validate_config
	check_ambient_urls
	ensure_layout
	init_cluster_if_needed
	cleanup_stale_runtime

	if pg_is_running; then
		write_env_file
		info "PostgreSQL already running for this worktree"
		return 0
	fi

	info "starting disposable PostgreSQL cluster"
	pg_ctl -D "$DATA_DIR" -w -l "$LOG_FILE" start >/dev/null
	export_local_env
	ensure_database_and_roles
	write_env_file
	info "SQLx PostgreSQL ready; source $ENV_FILE for DATABASE_URL values"
}

psql_as() {
	local user="$1"
	local db="$2"
	shift 2
	env -u PGPASSWORD \
		PGHOST="$SOCKET_DIR" \
		PGPORT="$PORT" \
		PGUSER="$user" \
		PGDATABASE="$db" \
		PGSSLMODE=disable \
		PGPASSFILE="$PGPASSFILE_PATH" \
		psql --no-password --no-psqlrc -v ON_ERROR_STOP=1 -X -q "$@"
}

psql_value() {
	local user="$1"
	local db="$2"
	local sql="$3"
	psql_as "$user" "$db" -Atc "$sql"
}

ensure_database_and_roles() {
	local app_ident admin_ident db_ident app_lit db_lit exists
	app_ident="$(quote_ident "$APP_USER")"
	admin_ident="$(quote_ident "$ADMIN_USER")"
	db_ident="$(quote_ident "$DB_NAME")"
	app_lit="$(sql_literal "$APP_USER")"
	db_lit="$(sql_literal "$DB_NAME")"

	if [[ "$(psql_value "$ADMIN_USER" postgres "SELECT 1 FROM pg_roles WHERE rolname = $app_lit")" != "1" ]]; then
		psql_as "$ADMIN_USER" postgres -c "CREATE ROLE $app_ident LOGIN"
	fi

	exists="$(psql_value "$ADMIN_USER" postgres "SELECT 1 FROM pg_database WHERE datname = $db_lit")"
	if [[ "$exists" != "1" ]]; then
		createdb --host="$SOCKET_DIR" --port="$PORT" --username="$ADMIN_USER" --owner="$ADMIN_USER" "$DB_NAME"
	fi

	psql_as "$ADMIN_USER" postgres -c "GRANT CONNECT ON DATABASE $db_ident TO $app_ident"
	psql_as "$ADMIN_USER" postgres -c "ALTER ROLE $app_ident IN DATABASE $db_ident SET search_path = ferrex, public"
	psql_as "$ADMIN_USER" postgres -c "ALTER ROLE $admin_ident IN DATABASE $db_ident RESET search_path"
}

create_sqlx_public_shadow_tables() {
	psql_as "$ADMIN_USER" "$DB_NAME" <<'SQL'
DO $$
DECLARE
  r record;
  public_kind text;
BEGIN
  FOR r IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'ferrex'
      AND c.relkind IN ('r', 'p')
      AND c.relname <> '_sqlx_migrations'
  LOOP
    SELECT c.relkind::text
    INTO public_kind
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = r.relname
    LIMIT 1;

    IF public_kind IS NULL THEN
      EXECUTE format('CREATE TABLE public.%I (LIKE ferrex.%I INCLUDING ALL)', r.relname, r.relname);
    END IF;
  END LOOP;
END $$;
SQL
}

grant_app_privileges() {
	local app_ident
	app_ident="$(quote_ident "$APP_USER")"

	psql_as "$ADMIN_USER" "$DB_NAME" <<SQL
GRANT CONNECT ON DATABASE $(quote_ident "$DB_NAME") TO $app_ident;
GRANT USAGE, CREATE ON SCHEMA ferrex TO $app_ident;
GRANT USAGE ON SCHEMA public TO $app_ident;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA ferrex, public TO $app_ident;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA ferrex, public TO $app_ident;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ferrex, public TO $app_ident;
ALTER DEFAULT PRIVILEGES IN SCHEMA ferrex GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO $app_ident;
ALTER DEFAULT PRIVILEGES IN SCHEMA ferrex GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO $app_ident;
ALTER DEFAULT PRIVILEGES IN SCHEMA ferrex GRANT EXECUTE ON FUNCTIONS TO $app_ident;
SQL
}

cmd_status() {
	require_pg_commands
	validate_config
	cleanup_stale_runtime

	if pg_is_running; then
		printf 'status: running\n'
	else
		printf 'status: stopped\n'
	fi
	printf 'workspace: %s\n' "$ROOT"
	printf 'state: %s\n' "$STATE_DIR"
	printf 'socket: %s/.s.PGSQL.%s\n' "$SOCKET_DIR" "$PORT"
	printf 'env: %s\n' "$ENV_FILE"
}

cmd_start() {
	start_postgres
}

cmd_migrate() {
	start_postgres
	require_sqlx_cli
	export_local_env

	info "running Ferrex SQLx migrations against disposable local database"
	(
		cd "$ROOT"
		SQLX_OFFLINE=false cargo sqlx migrate run --source "$MIGRATIONS_DIR" --database-url "$DATABASE_URL_ADMIN"
	)
	grant_app_privileges
	info "migrations complete"
}

cmd_prepare() {
	cmd_migrate
	require_sqlx_cli
	export_local_env

	create_sqlx_public_shadow_tables
	grant_app_privileges

	info "running cargo sqlx prepare with disposable local database"
	(
		cd "$ROOT"
		SQLX_OFFLINE=false cargo sqlx prepare --no-dotenv --workspace -- --all-features --all-targets "$@"
	)
}

cmd_prepare_check() {
	validate_config
	check_ambient_urls
	require_sqlx_cli

	info "running SQLx offline prepare check"
	(
		cd "$ROOT"
		env \
			-u DATABASE_URL \
			-u DATABASE_URL_ADMIN \
			-u PGHOST \
			-u PGPORT \
			-u PGUSER \
			-u PGDATABASE \
			-u PGSSLMODE \
			-u PGPASSFILE \
			-u PGPASSWORD \
			SQLX_OFFLINE=true \
			cargo sqlx prepare --no-dotenv --workspace --check -- --all-features --all-targets "$@"
	)
}

cmd_stop() {
	require_pg_commands
	validate_config

	if [[ ! -d "$DATA_DIR" ]]; then
		info "PostgreSQL state is absent for this worktree"
		return 0
	fi

	if pg_is_running; then
		info "stopping disposable PostgreSQL cluster"
		pg_ctl -D "$DATA_DIR" -m fast -w stop >/dev/null
	else
		info "PostgreSQL already stopped for this worktree"
	fi
	cleanup_stale_runtime
}

assert_safe_state_dir() {
	[[ -n "$STATE_DIR" && "$STATE_DIR" != "/" ]] || fail "refusing to remove unsafe state dir"
	[[ -f "$MARKER_FILE" ]] || fail "refusing to remove unmarked state dir: $STATE_DIR"
	grep -Fx "root=$ROOT" "$MARKER_FILE" >/dev/null || fail "state marker does not match this workspace"
}

cmd_reset() {
	validate_config
	check_ambient_urls
	if [[ -d "$STATE_DIR" ]]; then
		assert_safe_state_dir
		cmd_stop
		rm -rf "$DATA_DIR" "$RUN_DIR" "$LOG_DIR"
	fi
	cmd_migrate
}

cmd_destroy() {
	validate_config
	if [[ -d "$STATE_DIR" ]]; then
		assert_safe_state_dir
		cmd_stop
		rm -rf "$STATE_DIR"
		info "removed $STATE_DIR"
	else
		info "state already absent for this worktree"
	fi
	rm -f "$ENV_FILE" "$ENV_FILE.tmp"
	info "removed $ENV_FILE"
}

cmd_env() {
	write_env_file
	printf '%s\n' "$ENV_FILE"
}

cmd_psql() {
	start_postgres
	export_local_env

	local user="$APP_USER"
	if [[ "${1:-}" == "--admin" ]]; then
		user="$ADMIN_USER"
		shift
	fi
	psql_as "$user" "$DB_NAME" "$@"
}

main() {
	validate_config
	local command="${1:-help}"
	if [[ $# -gt 0 ]]; then
		shift
	fi

	case "$command" in
	start) cmd_start "$@" ;;
	status) cmd_status "$@" ;;
	migrate) cmd_migrate "$@" ;;
	prepare) cmd_prepare "$@" ;;
	prepare-check | check) cmd_prepare_check "$@" ;;
	stop) cmd_stop "$@" ;;
	reset) cmd_reset "$@" ;;
	destroy) cmd_destroy "$@" ;;
	env) cmd_env "$@" ;;
	psql) cmd_psql "$@" ;;
	help | --help | -h) usage ;;
	*)
		usage >&2
		fail "unknown command: $command"
		;;
	esac
}

main "$@"
