// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.files

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MediaFileMetadata : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MediaFileMetadata {
        __init(_i, _bb)
        return this
    }
    val duration : Double
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getDouble(o + bb_pos) else 0.0
        }
    val width : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val height : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val videoCodec : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val videoCodecAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun videoCodecInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val audioCodec : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val audioCodecAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun audioCodecInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    val bitrate : ULong
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val framerate : Double
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getDouble(o + bb_pos) else 0.0
        }
    val fileSize : ULong
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val colorPrimaries : String?
        get() {
            val o = __offset(20)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val colorPrimariesAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(20, 1)
    fun colorPrimariesInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 20, 1)
    val colorTransfer : String?
        get() {
            val o = __offset(22)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val colorTransferAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(22, 1)
    fun colorTransferInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 22, 1)
    val colorSpace : String?
        get() {
            val o = __offset(24)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val colorSpaceAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(24, 1)
    fun colorSpaceInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 24, 1)
    val bitDepth : UInt
        get() {
            val o = __offset(26)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    val parsedInfo : ferrex.files.ParsedMediaInfo? get() = parsedInfo(ferrex.files.ParsedMediaInfo())
    fun parsedInfo(obj: ferrex.files.ParsedMediaInfo) : ferrex.files.ParsedMediaInfo? {
        val o = __offset(28)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMediaFileMetadata(_bb: ByteBuffer): MediaFileMetadata = getRootAsMediaFileMetadata(_bb, MediaFileMetadata())
        fun getRootAsMediaFileMetadata(_bb: ByteBuffer, obj: MediaFileMetadata): MediaFileMetadata {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMediaFileMetadata(builder: FlatBufferBuilder, duration: Double, width: UInt, height: UInt, videoCodecOffset: Int, audioCodecOffset: Int, bitrate: ULong, framerate: Double, fileSize: ULong, colorPrimariesOffset: Int, colorTransferOffset: Int, colorSpaceOffset: Int, bitDepth: UInt, parsedInfoOffset: Int) : Int {
            builder.startTable(13)
            addFileSize(builder, fileSize)
            addFramerate(builder, framerate)
            addBitrate(builder, bitrate)
            addDuration(builder, duration)
            addParsedInfo(builder, parsedInfoOffset)
            addBitDepth(builder, bitDepth)
            addColorSpace(builder, colorSpaceOffset)
            addColorTransfer(builder, colorTransferOffset)
            addColorPrimaries(builder, colorPrimariesOffset)
            addAudioCodec(builder, audioCodecOffset)
            addVideoCodec(builder, videoCodecOffset)
            addHeight(builder, height)
            addWidth(builder, width)
            return endMediaFileMetadata(builder)
        }
        fun startMediaFileMetadata(builder: FlatBufferBuilder) = builder.startTable(13)
        fun addDuration(builder: FlatBufferBuilder, duration: Double) = builder.addDouble(0, duration, 0.0)
        fun addWidth(builder: FlatBufferBuilder, width: UInt) = builder.addInt(1, width.toInt(), 0)
        fun addHeight(builder: FlatBufferBuilder, height: UInt) = builder.addInt(2, height.toInt(), 0)
        fun addVideoCodec(builder: FlatBufferBuilder, videoCodec: Int) = builder.addOffset(3, videoCodec, 0)
        fun addAudioCodec(builder: FlatBufferBuilder, audioCodec: Int) = builder.addOffset(4, audioCodec, 0)
        fun addBitrate(builder: FlatBufferBuilder, bitrate: ULong) = builder.addLong(5, bitrate.toLong(), 0)
        fun addFramerate(builder: FlatBufferBuilder, framerate: Double) = builder.addDouble(6, framerate, 0.0)
        fun addFileSize(builder: FlatBufferBuilder, fileSize: ULong) = builder.addLong(7, fileSize.toLong(), 0)
        fun addColorPrimaries(builder: FlatBufferBuilder, colorPrimaries: Int) = builder.addOffset(8, colorPrimaries, 0)
        fun addColorTransfer(builder: FlatBufferBuilder, colorTransfer: Int) = builder.addOffset(9, colorTransfer, 0)
        fun addColorSpace(builder: FlatBufferBuilder, colorSpace: Int) = builder.addOffset(10, colorSpace, 0)
        fun addBitDepth(builder: FlatBufferBuilder, bitDepth: UInt) = builder.addInt(11, bitDepth.toInt(), 0)
        fun addParsedInfo(builder: FlatBufferBuilder, parsedInfo: Int) = builder.addOffset(12, parsedInfo, 0)
        fun endMediaFileMetadata(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
