// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.files

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MediaFile : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MediaFile {
        __init(_i, _bb)
        return this
    }
    val id : ferrex.ids.Uuid get() = id(ferrex.ids.Uuid())
    fun id(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            throw AssertionError("No value for (required) field id")
        }
    }
    val mediaIdType : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val mediaIdUuid : ferrex.ids.Uuid? get() = mediaIdUuid(ferrex.ids.Uuid())
    fun mediaIdUuid(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val path : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val pathAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun pathInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val filename : String
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field filename")
            }
        }
    val filenameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun filenameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val size : ULong
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    val discoveredAt : ferrex.common.Timestamp? get() = discoveredAt(ferrex.common.Timestamp())
    fun discoveredAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(16)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val createdAt : ferrex.common.Timestamp? get() = createdAt(ferrex.common.Timestamp())
    fun createdAt(obj: ferrex.common.Timestamp) : ferrex.common.Timestamp? {
        val o = __offset(18)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    val metadata : ferrex.files.MediaFileMetadata? get() = metadata(ferrex.files.MediaFileMetadata())
    fun metadata(obj: ferrex.files.MediaFileMetadata) : ferrex.files.MediaFileMetadata? {
        val o = __offset(20)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val libraryId : ferrex.ids.Uuid? get() = libraryId(ferrex.ids.Uuid())
    fun libraryId(obj: ferrex.ids.Uuid) : ferrex.ids.Uuid? {
        val o = __offset(22)
        return if (o != 0) {
            obj.__assign(o + bb_pos, bb)
        } else {
            null
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMediaFile(_bb: ByteBuffer): MediaFile = getRootAsMediaFile(_bb, MediaFile())
        fun getRootAsMediaFile(_bb: ByteBuffer, obj: MediaFile): MediaFile {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun startMediaFile(builder: FlatBufferBuilder) = builder.startTable(10)
        fun addId(builder: FlatBufferBuilder, id: Int) = builder.addStruct(0, id, 0)
        fun addMediaIdType(builder: FlatBufferBuilder, mediaIdType: Byte) = builder.addByte(1, mediaIdType, 0)
        fun addMediaIdUuid(builder: FlatBufferBuilder, mediaIdUuid: Int) = builder.addStruct(2, mediaIdUuid, 0)
        fun addPath(builder: FlatBufferBuilder, path: Int) = builder.addOffset(3, path, 0)
        fun addFilename(builder: FlatBufferBuilder, filename: Int) = builder.addOffset(4, filename, 0)
        fun addSize(builder: FlatBufferBuilder, size: ULong) = builder.addLong(5, size.toLong(), 0)
        fun addDiscoveredAt(builder: FlatBufferBuilder, discoveredAt: Int) = builder.addStruct(6, discoveredAt, 0)
        fun addCreatedAt(builder: FlatBufferBuilder, createdAt: Int) = builder.addStruct(7, createdAt, 0)
        fun addMetadata(builder: FlatBufferBuilder, metadata: Int) = builder.addOffset(8, metadata, 0)
        fun addLibraryId(builder: FlatBufferBuilder, libraryId: Int) = builder.addStruct(9, libraryId, 0)
        fun endMediaFile(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 12)
            return o
        }
    }
}
