// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.files

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ParsedEpisodeInfo : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ParsedEpisodeInfo {
        __init(_i, _bb)
        return this
    }
    val showName : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field showName")
            }
        }
    val showNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun showNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val season : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val episode : UShort
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val episodeTitle : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val episodeTitleAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun episodeTitleInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val year : UShort
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val resolution : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val resolutionAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(14, 1)
    fun resolutionInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 14, 1)
    val source : String?
        get() {
            val o = __offset(16)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(16, 1)
    fun sourceInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 16, 1)
    val releaseGroup : String?
        get() {
            val o = __offset(18)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val releaseGroupAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(18, 1)
    fun releaseGroupInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 18, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsParsedEpisodeInfo(_bb: ByteBuffer): ParsedEpisodeInfo = getRootAsParsedEpisodeInfo(_bb, ParsedEpisodeInfo())
        fun getRootAsParsedEpisodeInfo(_bb: ByteBuffer, obj: ParsedEpisodeInfo): ParsedEpisodeInfo {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createParsedEpisodeInfo(builder: FlatBufferBuilder, showNameOffset: Int, season: UShort, episode: UShort, episodeTitleOffset: Int, year: UShort, resolutionOffset: Int, sourceOffset: Int, releaseGroupOffset: Int) : Int {
            builder.startTable(8)
            addReleaseGroup(builder, releaseGroupOffset)
            addSource(builder, sourceOffset)
            addResolution(builder, resolutionOffset)
            addEpisodeTitle(builder, episodeTitleOffset)
            addShowName(builder, showNameOffset)
            addYear(builder, year)
            addEpisode(builder, episode)
            addSeason(builder, season)
            return endParsedEpisodeInfo(builder)
        }
        fun startParsedEpisodeInfo(builder: FlatBufferBuilder) = builder.startTable(8)
        fun addShowName(builder: FlatBufferBuilder, showName: Int) = builder.addOffset(0, showName, 0)
        fun addSeason(builder: FlatBufferBuilder, season: UShort) = builder.addShort(1, season.toShort(), 0)
        fun addEpisode(builder: FlatBufferBuilder, episode: UShort) = builder.addShort(2, episode.toShort(), 0)
        fun addEpisodeTitle(builder: FlatBufferBuilder, episodeTitle: Int) = builder.addOffset(3, episodeTitle, 0)
        fun addYear(builder: FlatBufferBuilder, year: UShort) = builder.addShort(4, year.toShort(), 0)
        fun addResolution(builder: FlatBufferBuilder, resolution: Int) = builder.addOffset(5, resolution, 0)
        fun addSource(builder: FlatBufferBuilder, source: Int) = builder.addOffset(6, source, 0)
        fun addReleaseGroup(builder: FlatBufferBuilder, releaseGroup: Int) = builder.addOffset(7, releaseGroup, 0)
        fun endParsedEpisodeInfo(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
