// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.files

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ParsedMovieInfo : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ParsedMovieInfo {
        __init(_i, _bb)
        return this
    }
    val title : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field title")
            }
        }
    val titleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun titleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val year : UShort
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    val resolution : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val resolutionAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(8, 1)
    fun resolutionInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 8, 1)
    val source : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val sourceAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(10, 1)
    fun sourceInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 10, 1)
    val releaseGroup : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val releaseGroupAsByteBuffer : ByteBuffer? get() = __vector_as_bytebuffer(12, 1)
    fun releaseGroupInByteBuffer(_bb: ByteBuffer) : ByteBuffer? = __vector_in_bytebuffer(_bb, 12, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsParsedMovieInfo(_bb: ByteBuffer): ParsedMovieInfo = getRootAsParsedMovieInfo(_bb, ParsedMovieInfo())
        fun getRootAsParsedMovieInfo(_bb: ByteBuffer, obj: ParsedMovieInfo): ParsedMovieInfo {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createParsedMovieInfo(builder: FlatBufferBuilder, titleOffset: Int, year: UShort, resolutionOffset: Int, sourceOffset: Int, releaseGroupOffset: Int) : Int {
            builder.startTable(5)
            addReleaseGroup(builder, releaseGroupOffset)
            addSource(builder, sourceOffset)
            addResolution(builder, resolutionOffset)
            addTitle(builder, titleOffset)
            addYear(builder, year)
            return endParsedMovieInfo(builder)
        }
        fun startParsedMovieInfo(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addTitle(builder: FlatBufferBuilder, title: Int) = builder.addOffset(0, title, 0)
        fun addYear(builder: FlatBufferBuilder, year: UShort) = builder.addShort(1, year.toShort(), 0)
        fun addResolution(builder: FlatBufferBuilder, resolution: Int) = builder.addOffset(2, resolution, 0)
        fun addSource(builder: FlatBufferBuilder, source: Int) = builder.addOffset(3, source, 0)
        fun addReleaseGroup(builder: FlatBufferBuilder, releaseGroup: Int) = builder.addOffset(4, releaseGroup, 0)
        fun endParsedMovieInfo(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
