// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.files

@Suppress("unused")
class ParsedMediaInfoVariant private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val ParsedMovieInfo: UByte = 1u
        const val ParsedEpisodeInfo: UByte = 2u
    }
}
