// automatically generated by the FlatBuffers compiler, do not modify

package ferrex.files

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ParsedMediaInfo : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ParsedMediaInfo {
        __init(_i, _bb)
        return this
    }
    val variantType : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun variant(obj: Table) : Table? {
        val o = __offset(6); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsParsedMediaInfo(_bb: ByteBuffer): ParsedMediaInfo = getRootAsParsedMediaInfo(_bb, ParsedMediaInfo())
        fun getRootAsParsedMediaInfo(_bb: ByteBuffer, obj: ParsedMediaInfo): ParsedMediaInfo {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createParsedMediaInfo(builder: FlatBufferBuilder, variantType: UByte, variantOffset: Int) : Int {
            builder.startTable(2)
            addVariant(builder, variantOffset)
            addVariantType(builder, variantType)
            return endParsedMediaInfo(builder)
        }
        fun startParsedMediaInfo(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addVariantType(builder: FlatBufferBuilder, variantType: UByte) = builder.addByte(0, variantType.toByte(), 0)
        fun addVariant(builder: FlatBufferBuilder, variant: Int) = builder.addOffset(1, variant, 0)
        fun endParsedMediaInfo(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
